### ISSUE TITLE
在js端怎样获取在服务端已经更换了的文件路径

### ISSUE THREAD

**Issue by SeanLee97** [fex-team/webuploader#1014]
在服务端已经将文件改名，请问怎么在js端获取到这些改名的文件路径呢？

**Comment by Edward-GU** [comment]
将你需要的数据在服务端输出，这样客户端就可以得到返回值，一般data，response，建议用json格式，解析._raw得到你所需要的数据，注意看官方API文档。

![image](https://cloud.githubusercontent.com/assets/12776939/8147416/791f7774-129b-11e5-8567-35be67114ed9.png)
