### ISSUE TITLE
怎么控制选择上传文件的数量？

### ISSUE THREAD

**Issue by jakeauyeung** [fex-team/webuploader#102]
RT

**Comment by wavelynn** [comment]
设置fileNumLimit为1，那么第一次上传成功了，再选择文件上传计数没有清零，然后报Q_EXCEED_NUM_LIMIT这个错误~

**Comment by joannaqq** [comment]
我想实现的是，选择上传的文件总数超过100或者某个值，则放弃这次上传

**Comment by joannaqq** [comment]
大家提的这个一致的问题有解决的吗？

**Comment by HQS1983** [comment]
我觉得把，这个移动端，例如微信发朋友圈，能控制选择的数量。
但是PC端还没法实现，弹出的窗口是多选就是多选，单选就是单选
