### ISSUE TITLE
如何获取后台传回的值

### ISSUE THREAD

**Issue by smartiu** [fex-team/webuploader#1066]
@RequestMapping("uploadPic")
	@ResponseBody
	public String uploadPic(@RequestParam(required=false)MultipartFile file){
			return "SUCCESS";
		}catch(SystemException e){
			throw new AjaxException(e);
		}catch(Exception e){
			throw new AjaxException("E0001",e.getMessage());
		}
	}

========================================
如上，后台返回SUCCESS在前端如何获取

目的需要把上传OK的图片绑定一个后台传回来的id，用来做后续的操作。

**Comment by yiwangqi** [comment]
uploadSuccess事件

参数
file  {File} File对象
response  {Object} 服务端返回的数据

**Comment by smartiu** [comment]
very 3q
