### ISSUE TITLE
上传参数想加入Authorization参数，如何编码，请来个DEMO

### ISSUE THREAD

**Issue by zhengjin** [fex-team/webuploader#1119]
在网上查的正常ajax应该如下：
$.ajax
({
  type: "GET",
  url: "index1.php",
  dataType: 'json',
  async: false,
  headers: {
    "Authorization": "Basic " + btoa(USERNAME + ":" + PASSWORD)
  },
  data: '{ "comment" }',
  success: function (){
    alert('Thanks for your comment!'); 
  }
});
或者
beforeSend: function (xhr) {
    xhr.setRequestHeader ("Authorization", "Basic XXXXXX");
},

不知道uploader是否支持，如何写？
非常感谢

**Comment by zhengjin** [comment]
或者有没有跨域的方案?

**Comment by 499978920** [comment]
初始化的时候，也加上 headers: { 'Authorization': 'xxxxx'}

**Comment by yangguangftlp** [comment]
请问如何在headers 中添加自定义参数哦，例如:abc:123
