### ISSUE TITLE
中文文件无法上传或者乱码问题？

### ISSUE THREAD

**Issue by kingrever** [fex-team/webuploader#115]
用示例中的例子上传文件，上传中文文件出现无法上传或者出现上传文件名乱码。而大文件上传文件名自动变成“”file_”什么的，什么原因？

**Comment by rudolph171** [comment]
我在IE8的情况下遇到文件名乱码的问题，请求参数已经乱码。官方的例子同样乱码，不知道是否和flash版本有关系。

**Comment by rudolph171** [comment]
通过修改flash源码解决了

**Comment by rudolph171** [comment]
也可以直接修改js源码，大致在6778、7831处直接对name参数进行url编码，这样方便些。
