### ISSUE TITLE
关于上传文件域和参数

### ISSUE THREAD

**Issue by majinhui04** [fex-team/webuploader#117]
1.请问如何在上传的时候添加多个参数一并发送到后台？
2.可不可以添加参数 修改 file 的name 用来后台接收

**Comment by michaelong** [comment]
能说明一下吗，我还是不了解，有人能分享吗?queebon@gmail.com

**Comment by ZheCheng** [comment]
@2betop 您好 我后台需要自定义一个type参数  我写在fromdata里面，但是它会被默认替换成文件的类型  怎么办 能不能默认不发文件类型
-----------------------------7815454723765
Content-Disposition: form-data; name="type"

**image/jpeg**我需要自定义

**Comment by iamziyue** [comment]
@2betop 
> options.fileVar: 'file', 用来控制file的name.
文档中是fileVal，但是设置不成功，像这样的：`fileVal:'upload',`，最后渲染出来总是name="file"这个默认值

**Comment by 940935011** [comment]
有两套系统，其中一套是文件资源管理，专门管理文件的，另一个是商品系统，现在要做的是从商品系统中跨域把图片上传到文件资源管理系统，但是上传失败！！

POST http://127.0.0.1:9083/yzl-image/image/upload/file

webuploader.js (第 6810 行)
"NetworkError: 403 Forbidden - http://127.0.0.1:9083/yzl-image/image/upload/file"
file
已阻止跨源请求：同源策略禁止读取位于 http://127.0.0.1:9083/yzl-image/image/upload/file 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。
