### ISSUE TITLE
如何在上传的时候自定义文件名？

### ISSUE THREAD

**Issue by Sheleng** [fex-team/webuploader#1172]
在上传文件的时候默认:

![webuploader](https://cloud.githubusercontent.com/assets/8438680/9220653/b21bb17e-4116-11e5-881b-18320f539136.png)

如何将红色箭头标注的内容替换成自定义的？

**Comment by tony618** [comment]
同问啊

**Comment by qzuser** [comment]
new WebUploader.Uploader({ 
fileVal: '自定义的文件名称'
})
这样 可以解决 亲测有效
