### ISSUE TITLE
webuploader 对微信端的浏览器支持是否有问题

### ISSUE THREAD

**Issue by JermeyYann** [fex-team/webuploader#1212]
![qq 20150829121048](https://cloud.githubusercontent.com/assets/13900367/9560444/fa73c5d2-4e46-11e5-8d27-767333b8298b.jpg)
在微信端上传图片之后捕获到的HttpPostedFile长度为零,这个有没有解决方案
![qq 20150829121434](https://cloud.githubusercontent.com/assets/13900367/9560457/9a09be94-4e47-11e5-9e43-5e0c65287048.jpg)

**Comment by zhouqr1993** [comment]
我也遇到这个问题了。。。上传时图片显示的是白图，服务器上查找图片显示图片错误，微信QQ都是这样。但是用手机自带浏览器就没这个问题

**Comment by JermeyYann** [comment]
已经解决, 使用二进制上传.
