### ISSUE TITLE
缩略图不能调整大小，只能是正方形吗

### ISSUE THREAD

**Issue by git-lt** [fex-team/webuploader#1213]
生成的缩略图都是100*100的图片，无法生成原大小的缩略图

**Comment by tmaccx** [comment]
// 缩略图大小
            thumbnailWidth = 100 * ratio,
            thumbnailHeight = 100 * ratio,

**Comment by git-lt** [comment]
@tmaccx 你好，请问这个配置是在哪里配置的，options里没有这项

**Comment by git-lt** [comment]
thumb {
    width: 110,
    height: 150
}
这样设置是无效的
