### ISSUE TITLE
WebUploader的API说的不是很清楚

### ISSUE THREAD

**Issue by MrLiJM** [fex-team/webuploader#1225]
例如：(1)限制单个文件长传的的大小属性的fileSingleSizeLimit的单位是什么，是KB、M还是其他
           (2)获取文件的状态没说明，使用file.Status()

**Comment by yuechen323** [comment]
B

**Comment by Alexcccc** [comment]
您好，能把你的JSP+Servlet写的简单的例子发我邮箱看看吗
122517976@qq.com
