### ISSUE TITLE
建议在 package.json 指定 "main" 字段

### ISSUE THREAD

**Issue by CodingMonkeyzh** [fex-team/webuploader#1227]
由于官方没有在 [npm](https://www.npmjs.com/) 上发布这个项目，目前只有一个 @jiyinyiyong  发布的 [tb-webuploader](https://www.npmjs.com/package/tb-webuploader)。由于目录与文件名不符，又没有在 `package.json` 下指定 `main`， 导致 `require('webuploader')` 不能正常的工作。

**Comment by jiyinyiyong** [comment]
我们在引用的时候用的是 `tb-webuploader/dist/webuploader`, 模块本身有多个文件需要导出, 还是自己写明比较合适.
