### ISSUE TITLE
选择图片按钮点击无响应

### ISSUE THREAD

**Issue by hfxu** [fex-team/webuploader#1233]
我把上传图片的div放在bootstrap的modal弹出层中，并且js中的初始化方法也运行了。但是其中的选择图片按钮，无法正常初始化。

div id="rt_rt_19ujbvhup18hq3ni1h4t1cvv13gn1" style="position: absolute; top: 0px; left: 0px; width: 1px; height: 1px; overflow: hidden;"

后来把webuploader.js中container的width和height改成定值，才可用，有没有更好的办法？
container.attr( 'id', 'rt_' + this.uid );
container.css({
                    position: 'absolute',
                    top: '0px',
                    left: '0px',
                    width: '86px',
                    height: '40px',
                    overflow: 'hidden'
                });

**Comment by WG-C** [comment]
+1 太浪费时间了

**Comment by PeakTai** [comment]
没有，我也遇到了。如果这个上传组件不自带样式，能让我们指定任意的元素，点击后进行上传就好了。
