### ISSUE TITLE
请问在上传文件的过程中，如何把想要传递的参数传递给服务器端

### ISSUE THREAD

**Issue by songtao2627** [fex-team/webuploader#1237]
比如说用户id

**Comment by mango163** [comment]
uploader = WebUploader.create({
            pick: {
                id: '#filePicker3',
                label: '点击选择图片'
            },
            formData: {
                uid: 123
            },
            dnd: '#dndArea3',
            paste: '#uploader3',
            swf: BASE_URL + '/js/Uploader.swf',
            chunked: false,
            chunkSize: 512 * 1024,
            disableGlobalDnd: true,
            fileNumLimit: 5,
            fileSizeLimit: 200 * 1024 * 1024,    // 200 M
            fileSingleSizeLimit: 50 * 1024 * 1024    // 50 M
        });
formdata就是

**Comment by songtao2627** [comment]
多谢
