### ISSUE TITLE
若两个人同时上传一个同名的很大的文件时，user_tmp会出现同名文件，如何解决？

### ISSUE THREAD

**Issue by kingrever** [fex-team/webuploader#126]

**Comment by w-rose** [comment]
uploadStart是文件上传之前触发，uploadBeforeSend是切片上传之前触发，这两个时间的触发顺序是怎样的？可以用deferred来控制异步顺序吗？
before-send-file和before-send也是文件上传之前和切片上传之前触发，和uploadStart,uploadBeforeSend有什么区别？
