### ISSUE TITLE
跨域请求的问题

### ISSUE THREAD

**Issue by i5hz** [fex-team/webuploader#1265]
应用服务和图片服务分别部署在不同的域下，如
app server: http://localhost:3000
image server: http://localhost:3721

客户端在uploadBeforeSend的回调中设置请求的头部，如
uploader.on('uploadBeforeSend', function(obj, data, headers) {
    _.extend(headers, {
"Origin": "http://localhost:3000",
"Access-Control-Request-Method": "POST"
    });
});

image server设置响应跨域的options请求，响应头部设为：
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Methods: get, post

实测发现客户端会触发uploadError事件，查看error原因是'abort‘，但实际文件已经上传成功，服务器已经接收到文件，但是客户端无法收到服务器端发回的响应。查看下面的文章显示webuploader应该是支持跨域请求的：

http://www.banghui.org/4373.html

是不是还需要配置什么参数？

**Comment by i5hz** [comment]
解决了，第二次post头部响应增加Access-Control-Allow-Origin: http://localhost:3000
https://github.com/fex-team/webuploader/issues/135

**Comment by flvy** [comment]
麻烦贴出配置的完整代码。另外，_.extend这个扩展方法具体是怎样的？

**Comment by allwellis** [comment]
如果自己没有说明白的请不要贴出来 误导人

**Comment by CharlesSong** [comment]
_.extend 这个应该是jquery 的$.extend

**Comment by dreamsk** [comment]
_.extend是Underscore.js的一个方法。。
