### ISSUE TITLE
webuploader上传的图片变大

### ISSUE THREAD

**Issue by pcazheng** [fex-team/webuploader#1343]
在使用webuploader时发现本地上传到服务器后 同一张图片服务器的比本地的大
而使用基本的form表单提交图片 图片大小 服务器跟本地的是一样的 
请问这个怎么解决

**Comment by nisnaker** [comment]
同遇到这个问题，不过issue好像没人看了。。。

**Comment by 505613913** [comment]
我的是大图,被压缩了,form表单跟原图一样

**Comment by lcat** [comment]
https://github.com/fex-team/webuploader/issues/1521
