### ISSUE TITLE
麻烦讲一下跨域的相关配置，谢谢！

### ISSUE THREAD

**Issue by overtrue** [fex-team/webuploader#135]
如题

**Comment by lazyhero** [comment]
跨域请求时 如何带上cookie ~~~ 
```javascript
xhrFields: {
                withCredentials: true
            }
```
有提供 类似这种的选项吗？

**Comment by xiaoji201509** [comment]
跨域请求时 如何带上cookie ~~~

xhrFields: {
                withCredentials: true
            }
有提供 类似这种的选项吗？

**Comment by leixu2txtek** [comment]
flash 的话，根目录要有一个 xml
如果是h5 他会先发送一个  option 请求


可以 google 一下  flash 跨域配置，以及h5 option请求 
 
 
------------------ 原始邮件 ------------------
发件人: "xiaoji201509"; 
发送时间: 2016年9月5日(星期一) 中午11:05
收件人: "fex-team/webuploader"; 
抄送: "Lei Xu"; "Comment"; 
主题: Re: [fex-team/webuploader] 麻烦讲一下跨域的相关配置，谢谢！ (#135)

 

跨域请求时 如何带上cookie ~~~
 
xhrFields: {
                 withCredentials: true
             }
 有提供 类似这种的选项吗？

**Comment by 437700418** [comment]
chrome浏览器不行呀     
![ei5f h bgv nukktazumqs](https://cloud.githubusercontent.com/assets/19658326/19254912/7020ed10-8f8b-11e6-8213-1732949d883d.png)

**Comment by leixu2txtek** [comment]
.NET 服务端要这么写

![default](https://cloud.githubusercontent.com/assets/5109966/19255458/da1e8d58-8f90-11e6-8541-c5b602a1ac86.png)

**Comment by etianqq** [comment]
"跨域请求时 如何带上cookie ~~~"

看源码发现，其实webuploader是提供跨域带cookie的选项的，直接如下配置即可：
var uploader = WebUploader.create({
        swf: '/lib/Uploader.swf',
        server: url,
        pick: '#picker',
        ...
        withCredentials: true  // 支持CORS跨域带cookie
    });

**Comment by 437700418** [comment]
chrome     就是有问题

**Comment by dzchen** [comment]
xhr.upload.onprogress为什么跨域的时候去掉进度就可以了，加上就提示错误？

**Comment by lincanbin** [comment]
@etianqq 的方法是可行的。

**Comment by DimonHo** [comment]
我也是chrome无法上传，在IE下面却可以。


![tim 20180526180211](https://user-images.githubusercontent.com/3371641/40574973-f5462554-610e-11e8-86fb-0a6c88fcd6fd.png)

我在后台设置了header
![image](https://user-images.githubusercontent.com/3371641/40574982-29309516-610f-11e8-8ff6-c3cf4bd9b05f.png)

**Comment by DimonHo** [comment]
问题解决了，不知道为什么，上面的过滤器写法似乎有些问题，后来换了一种写法居然就成功了：
![image](https://user-images.githubusercontent.com/3371641/40575210-5abd47b0-6113-11e8-967e-35d660911883.png)
