### ISSUE TITLE
一个图片正在上传（比较慢），点击上传按钮可以继续上传

### ISSUE THREAD

**Issue by whuhenrylee** [fex-team/webuploader#1357]
上传较慢的情况下，一个正在上传的按钮，点击上传可以继续再拉起选择框。
是否有方法可以在上传过程中让按钮不可点击或者禁用？

**Comment by whuhenrylee** [comment]
文档里没有，但是实例有一个disable和enable方法，看源代码发现的。搞定了

**Comment by walker-s** [comment]
调用了disable依然没有禁用
