### ISSUE TITLE
怎么调用flash运行环境获文件部分blob内容？

### ISSUE THREAD

**Issue by re2953** [fex-team/webuploader#1369]
filereader感觉更强大，我希望能直接调用flash环境获取blob内容，其他上传工具的flash环境（moxie等）可能是我调用不对，总是读取文件所有内容，导致内存占用过大，没法用。

	var file_part = file.source.slice(1011, 1100);
	var runtime = file_part.getRuntime();
	var a = runtime.flashExec('FileReader', 'readAsByteArray', file_part);

有了这个，我是不是就可以用ajax上传文件了？

**Comment by songguangyu** [comment]
但是好像这个方法用不了呀？
