### ISSUE TITLE
关于beforeFileQueued的问题

### ISSUE THREAD

**Issue by karliehgf** [fex-team/webuploader#1373]
在beforeFileQueued的时候，我要先进行一次异步判断，如果后台判断结果不允许上传，则中止当前上传过程，该怎么实现？在异步请求中如何设置beforeFileQueued的handle返回值为false？

**Comment by thecodeoflynn** [comment]
@karliehgf 这个你怎么做到的

**Comment by LSL1618** [comment]
beforeFileQueued只是加进队列前，并不是上传前。

**Comment by fangyuan-oo** [comment]
@karliehgf 想知道后来怎么解决的
