### ISSUE TITLE
怎么跳过某些分块？

### ISSUE THREAD

**Issue by mrzzcn** [fex-team/webuploader#139]
上传过程可能中断，总共10块，传了8块，下次上传如何跳过？

**Comment by pengliangzhong** [comment]
@2betop 
请问注册的before-send事件和uploadBeforeSend事件的执行先后顺序如何，js小白，望大师指点，谢谢！

**Comment by bisu328** [comment]
beforeSend: function(block){
                	   //分片验证是否已传过，用于断点续传
                    var task = new $.Deferred();
//                     var owner = this.owner;
                	   (new WebUploader.Uploader()).md5File(block.blob).progress(function(percentage){
                           console.log(percentage);
                       }).then(function(val){
//                     	   owner.options.formData.md5 = val;
//                     	   userInfo.md5 = val;
//                     	   md5 = val;
//                     	   block.chunkMd5 = val;
//                            console.log("chunkcheck md5:"+val);
                           $.ajax({
                               type: "POST", 
                               dataType:"text/json",
//                                url: backEndUrl ,
                               url: "http://localhost:8080/clouddisk/admin/files/chunkCheck",
       						data: {
                                   status: "chunkCheck", 
                                   chunkIndex: block.chunk,
                                   size: block.end - block.start, 
                                   md5: val
                               }
                               , cache: false
                               , timeout: 1000 //todo 超时的话，只能认为该分片未上传过
                               , dataType: "json"
                           }).then(function(data, textStatus, jqXHR){
                        	   console.log("chunkCheck:"+data.md5);
                               if(data.md5!=''){   //若存在，返回失败给WebUploader，表明该分块不需要上传
                            	   console.log("skip");
                                   task.reject();
                               }else{
                            	   console.log("noskip");
                                   task.resolve();
                               }
                           }, function(jqXHR, textStatus, errorThrown){    //任何形式的验证失败，都触发重新上传
                               task.resolve();
                           });
                           return $.when(task);
                           
                       });
                }

为什么我的代码执行到task.reject()不跳过分片，继续执行后面的上传分页的程序？？？？

**Comment by fengjianjunstudy** [comment]
@2betop 如何实现断点续传，传到一半的时候，断网了，网络恢复正常以后，手动触发继续上传，如何接着原来断开之处继续上传

**Comment by fengjianjunstudy** [comment]
@2betop 网络异常的情况下，分片重试三次，3次以后彻底失败，网络恢复正常以后我手动触发上传，uploader.upload() 
没有作用

**Comment by yinxiaoliang** [comment]
@beyondonly 
owner.md5File(block.blob)  分片指定start, end
`WebUploader.Uploader.register({
	    'before-send': 'checkchunk'
	}, {
	    checkchunk: function( block ) {
	        var deferred = WebUploader.Deferred();
	        var me = this, owner = this.owner;
	        
	        owner.md5File(block.blob,block.start, block.end)            
            .fail(function() {// 如果读取出错了，则通过reject告诉webuploader文件上传出错。
                deferred.reject();
            })           
            .then(function( md5 ) { // md5值计算完成
                // 与服务安验证
                $.ajax(owner.options.md5Server, {
                    dataType: 'json',
                    data: {
                    	chunk: block.chunk,
                    	chunks : block.chunks,
                    	start: block.start,
                    	end:   block.end,
                    	total: block.total,
                    	uid: owner.options.formData.uid,
                        md5: md5
                    },
                    success: function( response ) {
                        // 如果验证已经上传过
                        if ( response.exist ) {
                        	deferred.reject();
                            console.log('分片已传，跳过');
                        }else{
                        	 deferred.resolve();
                        }
                       
                    }
                });
            });
	        return deferred.promise();
	    }
	});`

**Comment by 15709186909** [comment]
暂停后再开始上传会丢失数据，丢失分片是什么原因？

**Comment by 15709186909** [comment]
暂停后再开始上传会丢失数据，丢失分片是什么原因？
