### ISSUE TITLE
一个图片压缩后size改变造成的无法在队列中删除文件的问题

### ISSUE THREAD

**Issue by the8th** [fex-team/webuploader#144]
之前用webuploader做上传，上传成功后如果调接口删除，发现无法再往队列中添加该图。经源码分析，发现问题如下：

控件在图片进入队列时利用图片名称，size，修改时间做了一个hash，用来标记文件是否在队列中。但是由于控件默认启用了压缩，导致压缩后图片尺寸改变，算出的hash和原来不等。造成无法删除，导致再次上传时，控件认为此文件依然存在。

**Comment by Liuhui11** [comment]
@2betop 你好，我用remove删除图片的时候，再次添加同张图片添加不成，这个是什么原因呢？
