### ISSUE TITLE
请问如何获得已选择的img的src值

### ISSUE THREAD

**Issue by fancyallen** [fex-team/webuploader#1479]
操作： 选择几张图片
问题：
1. 我在upload.js中的addFile方法后面使用uploader.getFiles()获得的文件信息，没找到图片的base64信息。getFiles不获取img的src值吗？
2. 我如何能够在我的html页面上取到这些img的src属性值 ？（重点问题）

**Comment by ANGULAR-X** [comment]
api里面有个makeThumb方法，可以获取base64Code                   
 $scope.getPic = function (file) {
                        uploader.makeThumb(file, function (error, src) {
                            if (error) {
                                return;
                            }
                            console.log(src);
                        }, 1, 1);
                    }

**Comment by fancyallen** [comment]
@ANGULAR-X  看到了，十分感谢。 之前直接用的下载下来的example封装好的初始化文件，所以没搞懂，现在自己弄个初始化去
