### ISSUE TITLE
ie9(及以下)使用无法加载flash按钮

### ISSUE THREAD

**Issue by xuexb** [fex-team/webuploader#148]
chrome正常, ie9以下点击demo无反应, 没有触发选择文件事件, flash版本是 13

**Comment by wangmeijian** [comment]
IE8/9无解？

**Comment by hugh87** [comment]
@2betop 大神，在ie8\9下一个页面加载多个上传组件的时候，出现“ 对象不支持“exec”属性或方法 ”错误。查看开发者工具，flash显示已加载，但是无法点击。求解！

**Comment by wangmeijian** [comment]
IE8/9下为什么无法选择文件？

**Comment by crazelee** [comment]
@wangmeijian IE8选择文件的问题你有解决吗

**Comment by 5thgfka** [comment]
![1](https://cloud.githubusercontent.com/assets/921099/7975725/00b33a36-0aa4-11e5-820e-840beee9567e.png)
这样算加载上了flash吗？但是点击它没效果呢？IE8 WIN7 64

**Comment by 5thgfka** [comment]
demo上可以点击弹出选择框出来

**Comment by 5thgfka** [comment]
https://github.com/fex-team/webuploader/zipball/master
我把这个包下载下来，点sample里的image-upload例子，右键按钮像上边那个图的效果，但是还是没有弹出选择文件的窗口。

**Comment by crazelee** [comment]
@5thgfka 要放到服务器中~

**Comment by aaronzhanghuahua** [comment]
飞

**Comment by aaronzhanghuahua** [comment]
放到服务器上了也不行

**Comment by luweimin** [comment]
大神，很有意思的一个问题，在网站demo设置IE8 9，点击上传图片能弹出选择文件框，我把网站保存到本地设置IE8 9模式，居然点击没反应，IE10 是没问题的。

**Comment by kimixyz** [comment]
ie8以下，上传图片有问题：
![qq 20150804144541](https://cloud.githubusercontent.com/assets/1740977/9054836/d6414402-3ab7-11e5-9030-bd547958113e.png)

**Comment by kellychenook** [comment]
为啥在线的demo在ie7+没问题呢，把项目包下载到本地在ie7+中点击选择图片按钮无反应呢。。。

**Comment by douhao1333** [comment]
很郁闷的，问题，我的系统是win7 32位 专业版，用谷歌，360，ie8打开官网的demo都没有问题，但是我自己写的例子在ie8下点击“选择文件”没有反应，在谷歌和360下运行没有问题，但是我如果设置runtimeOrder: 'flash',在谷歌和360下也是点击“选择文件”没有反应；我debug看页面没有报错，swf文件的路径也是正确的。

**Comment by liangsx** [comment]
@douhao1333 我也是。现在想在IE下用页面原型给用户演示一下都不可以，谷歌火狐可以。

**Comment by douhao1333** [comment]
@liangsx 我刚刚看了一下跟ie有关的issues，看到回答是，ie的话，你必须把项目放到服务器中才可以，我刚刚试了一下没成功，你可以试试看看看行不行;我现在在试这个#629这个的方法，把swf文件路径全写出来

**Comment by liangsx** [comment]
@douhao1333 确实放服务器下是可以。我们的客户现在拿到的只有静态文件，他们不是开发，不知道怎么搞服务器。

#629 试过了。swf:'d:/html/uploader.swf' 不可以

**Comment by douhao1333** [comment]
@liangsx 我的放在服务器都没有效果，不知道为什么了。。。。准备换一个swfupload

**Comment by VaJoy** [comment]
我这边是没法生成预览图啊郁闷

**Comment by th-520** [comment]
@2betop ie8 在http://fex.baidu.com/webuploader/demo.html  出现这种错误有解决方案么？
![baocuo](https://cloud.githubusercontent.com/assets/20639456/17097433/5a17dfac-5290-11e6-93be-59c0958261b2.png)

**Comment by JongShau** [comment]
电脑：win7 64 旗舰版   浏览器：IE9 
现象： 点击选择文件按钮无反应，页面coslole无报错 ，哪位大神有靠谱的解决方案

**Comment by JongShau** [comment]
IE10和IE11均没有问题

**Comment by litterGuy** [comment]
目前遇见了这个问题，在chrome下runtimeOrder: 'flash'使用flash。flash加载出来了，但是按钮的事件触发不了、无法打开选择文件框。
![image](https://user-images.githubusercontent.com/2154539/28859604-e4fa3244-778a-11e7-9cd2-dbf0743eb8d2.png)
主要是ie8、9下无法打开，所以在chrome下使用flash想做调试的

**Comment by make-dream** [comment]
flash加载完成，点击上传无响应，唤醒不了文件选择框，IE9就这样么

**Comment by navisoftware** [comment]
经确认这个问题是:这个地方要完整的结构,至少包含  extensions,mimeTypes.
accept: {
            title: 'Images',
            extensions: 'gif,jpg,jpeg,bmp,png',
            mimeTypes: 'image/*'
        },

被坑了几天,没办法只能扒官网demo,一句一句的调试后得出的. 没有这个:extensions IE9无法选择文件.

**Comment by zhangzhd** [comment]
我的问题是IE8下单击上传按钮没有反应，双击可以打开文件选择框。解决办法：把button标签 替换为了 div就ok了

**Comment by CainKane** [comment]
> chrome正常, ie9以下点击demo无反应, 没有触发选择文件事件, flash版本是 13

我也在低版本ie中遇到此问题 , 初步排查问题原因是 : webuploader感知到你选择的文件大小为0,是空文件,但其实不是  这应该是宿主环境模拟了Html5的File使得uploader误认为支持h5环境  造成的原因
