### ISSUE TITLE
关于webuploader 暂停问题与上传顺序问题

### ISSUE THREAD

**Issue by TiSongWen** [fex-team/webuploader#1498]
<h3>1.  暂停功能问题 

<strong>问题描述:</strong> 一键暂停是没什么问题的，当多文件上传(并且开启分片模式)时， 无法根据  stop(fileId) 来暂停某一个单一的文件（效果是：即时根据fileId, 也是暂停了所有的上传）

<h3>2. 上传功能问题

<strong>问题描述:</strong> 文件一键上传无问题, 但是文件上传功能好像只能是：上传完A(发送完A的信息后)，再去上传B，如果A没有上传完毕, 则B的进度永远为0;

均是分片上传; 还有一个小疑问：在google中跟踪代码的时候发现 webuploader.js中 me.pool 中存放了分片文件信息,  不知道 me.pool 的作用是什么 ？

主要是以上两个问题, 不知道是我哪里设置错参数了还是 该webuploader本身功能的问题，自己是学后台方向的，所以源码很多意义都暂时无法理解。这是大学里第一个项目额，需要用到大文件上传的功能，希望知道原因的话可以帮我一下。~嘿嘿 ^ ^

**Comment by songzeng2016** [comment]
请问第一个问题解决了吗，我也遇到同样的问题了
