### ISSUE TITLE
到底哪个才是上传暂停uploader.stop();uploader.stopUpload();

### ISSUE THREAD

**Issue by izhangzhihao** [fex-team/webuploader#1499]
到底哪个才是上传暂停uploader.stop();uploader.stopUpload();
用uploader.stop()的时候找不到该方法,断点续传的实现思路我懂，问题出在：如何实现暂停文件上传，然后再开始。现在的情况是，uploader.stop(true)后就无法继续，如果再调用uploader.upload()的话就变成了重上传了...........

**Comment by aehyok** [comment]
uploader.stop(true) 方法可以实现暂停吗

**Comment by izhangzhihao** [comment]
@aehyok那个是“终止”上传吧:sweat_smile:

**Comment by fubobing126** [comment]
uploader.stop(true) 这个方法确实无法暂停上传

**Comment by LSL1618** [comment]
其实就是停止当前文件或分片文件块上传，再次上传都是从当前文件或分片文件块重新开始的。断点续传倒是可以做到从未上传的那一部分开始上传，但是已经上传的那一部分还是需要向服务器确认是否已经上传，确认完后才从未上传的那一部分开始上传。

**Comment by summerlove66** [comment]
现在可以了，不过终止上传后，如何再继续呢
