### ISSUE TITLE
Uncaught Error: jQuery or Zepto not found!

### ISSUE THREAD

**Issue by maxdylan** [fex-team/webuploader#1502]
我是新手，刚接触，总报这个错误是什么原因呐，具体js应该怎么引，是不是我引用出了问题，css上的class名称和demo上的不符

**Comment by lyu910616** [comment]
话说你是不是应该注意引用顺序，比如jQ应该放在更靠前的位置。

发自我的 iPhone

**Comment by maxdylan** [comment]
是我自己的问题，果然是顺序问题，已经解决了，谢谢喽

**Comment by Mrwangfan** [comment]
我也是一直是这个错   你的是怎么解决的 方便粘代码出来吗   vue的话 该怎么引用webuploader

**Comment by maxdylan** [comment]
很久了，不太记得了，好像就是jq的位置问题，你把jq的引用放到最上面试试

**Comment by yfsola** [comment]
@Mrwangfan请问你的问题解决了吗
