### ISSUE TITLE
ie8、9下，上传文件失败，提示：错误码http

### ISSUE THREAD

**Issue by kui1993** [fex-team/webuploader#1522]
详细错误提示：上传失败! 文件:1.jpg 错误码:http

**Comment by kui1993** [comment]
问题解决了，是Uploader.swf的路径写错了。不知道为什么在同文件夹下不能写成这样：swf:'Uploader.swf'，要写成：**swf:'/js/Uploader.swf'**，才能引用到Uploader.swf。

**Comment by zhenzi887** [comment]
examples\image-upload这个案例在ie8、9下有问题，点击选择图片没有反应，Uploader.swf的路径是对的
