### ISSUE TITLE
图片裁剪功能对png格式图片无效

### ISSUE THREAD

**Issue by ab1015** [fex-team/webuploader#1524]
貌似只支持jpg格式图片

```
compress : {
    width: 120,
    height: 120,
    quality: 90,
    allowMagnify: false,
    crop: true
}
```

**Comment by aihaiyue123** [comment]
对啊，这怎么弄？今天我也发现了这个问题

**Comment by ab1015** [comment]
你好，我们现在的图片裁剪都是自己通过canvas裁剪的，然后转换成jpg格式的图片再使用webuploader上传。
---- 原始邮件 ----

**Comment by lihua123569** [comment]
源码里找到这个位置
 beforeSendFile    
如下粗体为添加的，就可以实现了
// 只压缩 jpeg 图片格式。
                // gif 可能会丢失针
                // bmp png 基本上尺寸都不大，且压缩比比较小。
                if ( !opts || !~'image/jpeg,image/jpg**,image/png,image/gif,image/bmp**'.indexOf( file.type ) ||
                        file.size < compressSize ||
                        file._compressed ) {
                    return;
                }
