### ISSUE TITLE
官网demo上传文件时不能暂停

### ISSUE THREAD

**Issue by senola** [fex-team/webuploader#157]
测试浏览器：谷歌，版本 34.0.1847.116 m；
操作：选择较大文件，点击上传，进度条前进一段后点击暂停。
现象：进度条仍然在走，没有停止上传。

貌似暂停功能不能用，最近需要用到这个功能，麻烦看一下！！

**Comment by wodexiaoxixi14** [comment]
@2betop  就像是   @phgczm 说的，分片时，设置为true也不管用，还是会上传完正在上传的文件，请问怎么解决呢？      @phgczm 解决了吗？求方案

**Comment by LwcReber** [comment]
@2betop 
关于stop有两种模式的解答，尝试第二种true参数的方式，但是看到当前上传网速一直是占用很大的宽带，
然后重新上传其他文件时，显示上传状态为上传中，并没有开始上传。等到stop的那个文件上传完毕了，重新上传的文件才开始上传。所以，我觉得stop的第二种模式并没有中断当前文件上传。
想问下这个为什么没有中断上传呢，
用的是现在最新版的库。谢谢

**Comment by aehyok** [comment]
@LwcReber  请问问题解决了嘛
