### ISSUE TITLE
Uncaught TypeError: flash.exec is not a function

### ISSUE THREAD

**Issue by cevin** [fex-team/webuploader#1575]
this.flashExec = function( comp, fn ) {
                var flash = me.getFlash(),
                    args = Base.slice( arguments, 2 );
    
                return flash.exec( this.uid, comp, fn, args );
            };

nolog.js:7650

**Comment by 472630126** [comment]
我也是遇到这个问题 。。你解决了吗

**Comment by cevin** [comment]
@472630126  flash的按钮从始至终不能被隐藏或删除。- -#  否则就会出现这个问题。
