### ISSUE TITLE
Base.Deferred is not a function 请问是什么问题？

### ISSUE THREAD

**Issue by wangpengfei15975** [fex-team/webuploader#1585]
webUploader.js出现以下错误TypeError: Base.Deferred is not a function，deferred = Base.Deferred(); 请问是什么问题？

**Comment by Rockergmail** [comment]
这种情况我遇到过，我当时是引用了zepto，改为jquery就好了

**Comment by wangpengfei15975** [comment]
@Rockergmail 是zepto里没有Deferred的插件 解决了 。。

**Comment by wumin123150** [comment]
增加callbacks和deferred模块
