### ISSUE TITLE
必须要引入jquery或zepto库吗？

### ISSUE THREAD

**Issue by shawon1220** [fex-team/webuploader#1587]
必须要引入jquery或zepto库吗？ 好像在文档里面一直没有体现出来啊。。。

**Comment by LSL1618** [comment]
@shawon1220 ，要的，源码里边有用到。

**Comment by shawon1220** [comment]
我看文档说明jquery替代实现，但是看源码应该还没有完成吧，我想在react项目中直接使用呢，不依赖jquery多好啊。

**Comment by jackyon** [comment]
在react项目确实是硬伤呀，react基本不需要用到jquery库。
