### ISSUE TITLE
不支持指定接受csv类型文件过滤过滤

### ISSUE THREAD

**Issue by zxfcp** [fex-team/webuploader#1592]
accept: {
  // 可以上传的文件类型
  title: 'doc', // 文字描述
  extensions: '.csv',
  mimeTypes: 'text/csv'
},
accept属性这样配置，但是点击上传选择文件时，什么类型的文件都可以看到，没有过滤掉非csv文件

**Comment by swxy** [comment]
accept: {
                        title: 'CSV',
                        extensions: 'csv',
                        mimeTypes: 'text/csv,application/csv,text/comma-separated-values'
                    },
