### ISSUE TITLE
中途需要改变上传文件类型

### ISSUE THREAD

**Issue by zxfcp** [fex-team/webuploader#1593]
需要支持excel,text,csv三种文件类型,因为需要支持拖拽，所以webuploader初始化时需要create,并且指定文件上传类型。
但是，
![image](https://cloud.githubusercontent.com/assets/5679552/13834959/3d293fee-ec2e-11e5-8522-4a8b372c1474.png)
我点击某个类型文件时，需要过滤掉非这种类型的文件，怎么样在点击的时候设置webuploader改变accept的指定类型

**Comment by LSL1618** [comment]
@zxfcp ，可以的。
`uploader.options.accept.extensions = "gif,jpg,jpeg,bmp,png";`

**Comment by zxfcp** [comment]
@LSL1618 不行的，
![image](https://cloud.githubusercontent.com/assets/5679552/13845073/8e0e7c40-ec78-11e5-9cee-d29e45635f99.png)
选择文件弹出框还是出现的所有文件
![image](https://cloud.githubusercontent.com/assets/5679552/13845121/c6942d3a-ec78-11e5-9d23-b4c626676723.png)

**Comment by LSL1618** [comment]
@zxfcp ，这个过滤只能是选了文件后才有作用。

**Comment by zxfcp** [comment]
@LSL1618 好吧，我要的是选择的时候就过滤了，jQuery("#filePicker input:file").attr('accept','.txt'); 只能这样搞了，强制弹出时过滤文件，谢谢了

**Comment by marc126** [comment]
uploader.option('accept',{......})  这样无效呀

**Comment by LSL1618** [comment]
@marc126 ，你写错了吧，是这样uploader.options.accept.extensions = "gif,jpg,jpeg,bmp,png";
