### ISSUE TITLE
一个页面有多个上传，后端如何区分？

### ISSUE THREAD

**Issue by xiasun** [fex-team/webuploader#1613]
假设一个页面有两个上传按钮，对于这两个按钮上传的文件，后端需要分别按不同方式处理。请问有什么参数可以用吗？
目前只发现了一个ID，是WU_FILE_0，WU_FILE_1...这样的，但它是根据上传先后来的。是否可以对没一个上传按钮绑定一个额外的参数用于后端的识别呢？求大神指教。

**Comment by xiasun** [comment]
已经知道了,可以用formData参数设置.

**Comment by x-a** [comment]
一个按钮怎么区分不同类型的附件?
