### ISSUE TITLE
webpack与webuploader 一起使用的报错： jQuery or Zepto not found

### ISSUE THREAD

**Issue by xiabin** [fex-team/webuploader#1635]
我通过webpack独自以这样的方式:    require('js-dir/lib/webuploader/webuploader.min.js') 加载的时候会有这样的报错，补充下jquery我是提前加载进去了的

**Comment by xiabin** [comment]
require('expose?$!expose?jQuery!jquery');
require('script!../lib/webuploader/webuploader.js')
这样可以解决

**Comment by meakchen** [comment]
这个解决方式需要expose 相关的模块吧

**Comment by xiabin** [comment]
是的

**Comment by Mrwangfan** [comment]
vue2.0怎么引用 百度这个 webuploader  插件  具体的谢谢！

**Comment by Mrwangfan** [comment]
import  '../../lib/jquery/jquery-2.2.4.min.js';
import  '../../lib/webuploader/webuploader.css';
import  '../../lib/webuploader/webuploader.min.js';    
我是这样引用的   但是报错 Uncaught Error: jQuery or Zepto not found!    （vue 新手 求教 ）
