### ISSUE TITLE
刚下的最新版为什么提示我 this._init is not a function

### ISSUE THREAD

**Issue by pkptzx** [fex-team/webuploader#1637]
提示 this._init is not a function 
是什么原因?

**Comment by lonesomeme** [comment]
我也是这个问题 你解决了吗

**Comment by chocking** [comment]
我也是这个问题 为什么close了啊

**Comment by CAI2H** [comment]
error：var uploader = WebUploader.Uploader
correct ：var uploader = new WebUploader.Uploader

**Comment by wolfsheep** [comment]
我这边按照demo里面引用相关js以及css，执行了js语句后，没有任何作用，楼主是怎么做的？
