### ISSUE TITLE
IE8 版本号 8.0.7601.17514 只有jpg文件能上传其他文件都显示上传失败，但是服务器端正常

### ISSUE THREAD

**Issue by konanzheng** [fex-team/webuploader#1657]
问题描述：在ie8 下，只能上传jpg图片成功，上传其他格式图片或者其他文件都会触发uploadError事件，后台服务器调试发现是上传成功的也返回了生成的uuid，但是前台接收不到，uploadSuccess事件没触发，uploadError事件处理函数接收到的reponse参数也没有服务器返回的任何信息只有"http" ,使用的是example中的例子做的测试。

**Comment by konanzheng** [comment]
最后通过调试源码发现错误码http隐藏了http状态是406
发现 问题所在自己直接在源码上hack 设置Accept="*/*" 来解决了ie8 下的问题

**Comment by CMCXY0321** [comment]
@konanzheng 怎么hack的呢

**Comment by CMCXY0321** [comment]
@konanzheng 如何hack的，求教

**Comment by konanzheng** [comment]
@CMCXY0321  我是直接改的代码，https://github.com/fex-team/webuploader/pull/1664
