### ISSUE TITLE
require('../assets/plugin/webuploader/webuploader.html5only.min'); 引入出错！

### ISSUE THREAD

**Issue by ickeep** [fex-team/webuploader#1691]
require('../assets/plugin/webuploader/webuploader.html5only.min'); 引入出错！
Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

**Comment by NauxChen** [comment]
我也遇到相同的问题，单情况可能和你不一样，希望有帮助
```js 
import 'jquery'
import WebUploader from 'libs/webuploader.html5only.js'
```

webpack   
```js
{
            test: /\.js$/,
            loader: 'babel',
            include: projectRoot,
            exclude: /node_modules/
}
```

经过BABEL, 使用了ES6 的导入模块方式 ， ES6 Module 默认 strict模式，我的解决思路：   
不让他经过 babel  
loader 配置改为
```js
{
            test: /\.js$/,
            loader: 'babel',
            include: projectRoot,
            exclude:/(node_modules|webuploader.html5only)/
}
```

比较好的方式是 不用`aguments.callee`，这个得改代码 >_<

**Comment by azumia** [comment]
@NauxChen 
 试过成功了，谢谢！

**Comment by sunnut** [comment]
> 我也遇到相同的问题，单情况可能和你不一样，希望有帮助
> 
> ```js
> import 'jquery'
> import WebUploader from 'libs/webuploader.html5only.js'
> ```
> 
> webpack
> 
> ```js
> {
>             test: /\.js$/,
>             loader: 'babel',
>             include: projectRoot,
>             exclude: /node_modules/
> }
> ```
> 
> 经过BABEL, 使用了ES6 的导入模块方式 ， ES6 Module 默认 strict模式，我的解决思路： 不让他经过 babel loader 配置改为
> 
> ```js
> {
>             test: /\.js$/,
>             loader: 'babel',
>             include: projectRoot,
>             exclude:/(node_modules|webuploader.html5only)/
> }
> ```
> 
> 比较好的方式是 不用`aguments.callee`，这个得改代码 >_<

这个是啥意思啊：比较好的方式是 不用`aguments.callee`，这个得改代码
