### ISSUE TITLE
如何自己封装一个File对象添加至上传队列呢？

### ISSUE THREAD

**Issue by a736921** [fex-team/webuploader#1698]
请问该如何处理这个需求呢？

**Comment by fyee** [comment]
var getFileBlob = function (url, cb) {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", url);
        xhr.responseType = "blob";
        xhr.addEventListener('load', function() {
            cb(xhr.response);
        });
        xhr.send();
};

var blobToFile = function (blob, name) {
        blob.lastModifiedDate = new Date();
        blob.name = name;
        return blob;
};

var getFileObject = function(filePathOrUrl, cb) {
       getFileBlob(filePathOrUrl, function (blob) {
          cb(blobToFile(blob, 'test.jpg'));
       });
};

getFileObject('img/test.jpg', function (fileObject) {
     console.log(fileObject);
//replace console with  uploader.addfile(fileobject)
});

**Comment by a736921** [comment]
@fyee 太感谢了，完美的实现了我要的功能。因为已经写好了文件选择不希望再改动了。而且在Android下面是不支持文件多选的。

**Comment by SNull** [comment]
你这个解决方案适合于小文件，然而我这边的文件都是上GB的，不可能去去读取下来，怎么解决?!

**Comment by Troland** [comment]
@fyee 要是图片是跨域的就不行了，比如放在cdn上面会出现无法通过跨域加载图片
