### ISSUE TITLE
webuploader 0.1.6 上传图片有些限制有问题请问怎么处理

### ISSUE THREAD

**Issue by wang3156** [fex-team/webuploader#1754]
你好，我使用了webuploader 0.1.6的，但我设置好FileNumLimit 参数后，第一次和第二次选择文件正常，第三次选择文件就会超出我设置的数量请问是什么原因。另外我调用了removeFile移除了所以文件后调用getFiles时所有的文件都还在里面请问怎么处理，再我上传失败的文件就无法再次上传了用File.setStatus设置状态也没用

**Comment by alongchengtian0** [comment]
测试了一下，不会产生你说的这个问题。

**Comment by wang3156** [comment]
我是用可是在我这真的出了，请问可能是什么原因造成的，我在win7  ie11中做的，文件选择时每一次我都是选择超过我限制张数的文件，上传完后将文件移除，是否是我移除方法有问题，可否借你的代码参考一下

**Comment by wang3156** [comment]
已经处理，我原来是直接用getFiles获取所有上传成功的文件，然后再用removeFile去移除，现在改到success事件中，处理完一个就直接用removeFile移除掉就正常了
