### ISSUE TITLE
粘贴功能只能在chrome使用吗

### ISSUE THREAD

**Issue by gorilahe** [fex-team/webuploader#178]
测试了下，在firefox29和ie中都使用不了粘贴功能

**Comment by xinyuanyu** [comment]
这个问题有任何的update吗？找了一些其他的库，貌似粘贴功能都只支持chrome

**Comment by zhouzefei** [comment]
@2betop 
windows chrome：58.0.3029.81
我打开mac中开虚拟机，windows下的chrome，，不能从文件夹中复制粘贴到网页中
http://fex.baidu.com/webuploader/demo.html
