### ISSUE TITLE
如果要支持多种文件格式，Accept应该怎么设置呢？

### ISSUE THREAD

**Issue by EricInSH** [fex-team/webuploader#1783]
accept: {
                 title: 'logfile',
                 extensions: 'tar,txt,zip',
                 mimeTypes: 'text/plain,application/zip'
             },

这样设置可以吗？

**Comment by alongchengtian0** [comment]
**如果这样设置已经可以上传成功，请关闭 **

**Comment by EricInSH** [comment]
可以上传
