### ISSUE TITLE
ie 8 兼容问题

### ISSUE THREAD

**Issue by dudu123123** [fex-team/webuploader#1787]
ie 8 下上传图片按钮点击没反应  调试程序报 对象不支持 exec属性或方法

**Comment by alongchengtian0** [comment]
**截图一下?**

**Comment by dudu123123** [comment]
![Uploading image.png…]()

**Comment by dudu123123** [comment]
![qq 20160615131819](https://cloud.githubusercontent.com/assets/19941800/16068750/169a0598-32fb-11e6-8b69-3b998eab7e27.png)

**Comment by dudu123123** [comment]
点选择图片没有反应  是在360浏览器  ie8的兼容模式下

**Comment by alongchengtian0** [comment]
1.查看一下“网络”那个标签里，是否有Uploader.swf 文件没正确加载。
2.360浏览器中建议加入**<meta name="renderer" content="webkit">**，[360meta标签文档](http://se.360.cn/v6/help/meta.html)。

**Comment by wkIconFontLib** [comment]
我出的也是这样的问题，我这边 @alongchengtian0 根据你的已经加了也不好使

**Comment by pangzhuanxia** [comment]
请你你最后怎么解决的
