### ISSUE TITLE
IE8下png的缩略图不显示/选中超限图片能否给个错误提示

### ISSUE THREAD

**Issue by xiao-hai** [fex-team/webuploader#179]
IE8下png的缩略图不显示，jpg正常，看起来是src没值，不知道是不是转base64出了问题；
我设置了单张图片的最大体积，超大的图片虽然不能添加进队列，但是我想确定以后给个提示，要不然看起像是插件出了问题。

**Comment by lihua123569** [comment]
我用的最新的不行呢，dist/webuploader.js ---WebUploader 0.1.6 ？？
