### ISSUE TITLE
0.1.6版本，在ie8，9中上传时选择图片超过三张时报错

### ISSUE THREAD

**Issue by wang3156** [fex-team/webuploader#1798]
0.1.6版本，在ie8，9中上传时选择图片超过三张时报错，选择时报错位置webuploader.js中me.on('all',function (type){  中执行switch  case的change时报的错，然后就是flash报未指明错误，instance.CallFunction时instance为null，然后报错can't add external files。     三张以下操作正常

**Comment by wang3156** [comment]
暂时不知道不什么因为dome里是正常的所以先关闭了

**Comment by kevin123de** [comment]
楼主，问题解决了吗 ？
