### ISSUE TITLE
文件上传之前的MD5校验

### ISSUE THREAD

**Issue by zhaoliuzi** [fex-team/webuploader#180]
请问文件上传之前的MD5校验如何做？ 有相关的API提供么？

**Comment by bisu328** [comment]
beforeSend: function(block){
                	   //分片验证是否已传过，用于断点续传
                    var task = $.Deferred();
                	   (new WebUploader.Uploader()).md5File(block.blob).progress(function(percentage){
                           console.log(percentage);
                       }).then(function(val){
                    	   alert(val);
                    	   userInfo.md5 = val;
                    	   md5 = val;
                    	   block.chunkMd5 = val;
                           console.log("chunkcheck md5:"+val);
                           $.ajax({
                               type: "POST", 
                               dataType:"text/json",
//                                url: backEndUrl ,
                               url: "http://localhost:8080/clouddisk/admin/files/chunkCheck",
       						data: {
                                   status: "chunkCheck", 
//                                    name: uniqueFileName, 
                                   chunkIndex: block.chunk,
                                   size: block.end - block.start, 
                                   md5: val
                               }
                               , cache: false
                               , timeout: 1000 //todo 超时的话，只能认为该分片未上传过
                               , dataType: "json"
                           }).then(function(data, textStatus, jqXHR){
                        	   console.log(data);
                        	   console.log("chunkCheck:"+data.md5);
                               if(data.ifExist){   //若存在，返回失败给WebUploader，表明该分块不需要上传
                                   task.reject();
                               }else{
                                   task.resolve();
                               }
                           }, function(jqXHR, textStatus, errorThrown){    //任何形式的验证失败，都触发重新上传
                               task.resolve();
                           });
                           return $.when(task);
                           
                       });
                }
                , afterSendFile: function(file){
                    var chunksTotal = 0;
                    if((chunksTotal = Math.ceil(file.size/chunkSize)) > 1){
                        //合并请求
                        var task = new $.Deferred();
                        $.ajax({
                            type: "POST", 
                            dataType:"text/json",
//                             url: backEndUrl ,
                            url: "http://localhost:8080/clouddisk/admin/files/chunksMerge" ,
                            data: {
                                status: "chunksMerge" , 
//                                 name: uniqueFileName, 
                                chunks: chunksTotal, 
                                ext: file.ext, 
                                md5: md5Mark
                            }
                            , cache: false
                            , dataType: "json"
                        }).then(function(data, textStatus, jqXHR){
                            //todo 检查响应是否正常
                            task.resolve();
                            file.path = data.path;
                            UploadComlate(file);
                        }, function(jqXHR, textStatus, errorThrown){
                            task.reject();
                        });
                        return $.when(task);
                    }
                    else{
                        UploadComlate(file);
                    }
                }
            });

			var uploader = WebUploader.create({
				swf: "Uploader.swf"
				, server: backEndUrl
				, pick: "#picker"
				, resize: false
				, dnd: "#theList"
				, paste: document.body
				, disableGlobalDnd: true
				, thumb: {
					width: 100
					, height: 100
					, quality: 70
					, allowMagnify: true
					, crop: true
					//, type: "image/jpeg"
				}
请问如何把分片的chunkcheck 的md5值 ，传给backurl上传文件的方法里？？？？
