### ISSUE TITLE
如何替换上传按钮的样式

### ISSUE THREAD

**Issue by chenlong11** [fex-team/webuploader#1803]
如题，如何替换上传按钮的样式，比如我要将按钮换一种展示方式，按照api做了相应的配置，貌似没起作用

**Comment by superhanliu** [comment]
哪个api可以做配置啊？我也想用啊。
或者加个ready事件在uploader初始化成功后触发也行啊。这样我可以在成功的瞬间动态修改ui。

**Comment by kevin123de** [comment]
采取覆盖的方式

**Comment by hejisan** [comment]
怎样自定义上传按钮样式 · Issue #1472 · fex-team_webuploader.html

**Comment by hejisan** [comment]
http://blog.csdn.net/hejisan/article/details/79390344 请看第四大点
