### ISSUE TITLE
WebUploader 怎么修改成在整个表单提交的时候才去上传选中的文件？

### ISSUE THREAD

**Issue by newline2010** [fex-team/webuploader#1851]
想做成使用webuploader选择好文件，然后在页面表单提交的时候，才去上传文件。这个该在什么地方修改呢。

**Comment by newline2010** [comment]
C#

**Comment by liiana** [comment]
自动上传关掉 手动调用upload（）方法
` auto: false`
`uploader.upload();`

**Comment by newline2010** [comment]
> 自动上传关掉 手动调用upload（）方法
> `auto: false`
> `uploader.upload();`
