### ISSUE TITLE
PNG背景图片透明，上传预览中背景变黑

### ISSUE THREAD

**Issue by kirangels888** [fex-team/webuploader#1857]
请问这个问题如何解决？在http://fex.baidu.com/webuploader/getting-started.html  中尝试,预览也是背景黑色。

**Comment by kirangels888** [comment]
忘记搜索一下便提问题了，现在已解决，https://github.com/fex-team/webuploader/issues/1714

**Comment by wangshikun2010** [comment]
预览的缩略图任何格式都不用设置，就不用强制转换了，参考链接[http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_options](http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_options)
中thumb选项的配置

**Comment by lxhmm921** [comment]
将type设置为空，上传后的背景色还是黑色，请问大神们如何解决的
