### ISSUE TITLE
关于uploader.on( 'uploadAccept', function( file, response )

### ISSUE THREAD

**Issue by unityProcessWang** [fex-team/webuploader#1924]
uploader.on( 'uploadAccept', function( file, response ) {
        
          alert("有数据");
            if ( response['error']['code']!=null ) {
                // 通过return false来告诉组件，此文件上传有错。
                
                return false;
            }
            else
            {
                alert("无数据");
                return true;
            }
        });

如果是没有错误  他不执行else

**Comment by unityProcessWang** [comment]
病急乱投医了   我应该是数组那为空了

**Comment by alongchengtian0** [comment]
说明 response['error']['code']!=null 还是为true，response['error']['code']这个值可能是undefined或者是空字符串
