### ISSUE TITLE
安卓微信内置浏览器无法上传图片

### ISSUE THREAD

**Issue by FE-CCY** [fex-team/webuploader#197]
微信浏览器中无法上传图片，请问有什么样的兼容方案？

**Comment by honglio** [comment]
@lilo202 大于50K图片不能上传，用二进制方案可以解决吗？

**Comment by ysj40540** [comment]
我自己写的webview为什么点击没有反应？ 微信却可以选择文件？

**Comment by TuLe1** [comment]
部分安卓机器上微信内置浏览器可以选择文件并上传,但是部分安卓机器不可以（微信内置浏览器不可以选择文件上传,使用UC浏览器又可以选择文件上传）请问有人知道是为什么嘛？

**Comment by duoni** [comment]
前几天都能上传 大概2019.03.01开始 安卓微信内置浏览器无法选择图片文件上传，使用UC浏览器可以，求解决方案

**Comment by LianJion** [comment]
https://github.com/fex-team/webuploader/issues/197#issuecomment-469520232

针对微信设置 image/* 试试看

**Comment by duoni** [comment]
> [#197 (comment)](https://github.com/fex-team/webuploader/issues/197#issuecomment-469520232)
> 
> 针对微信设置 image/* 试试看

感谢，测试可以。。。坑爹微信
