### ISSUE TITLE
stop 或cancelFile 后出现异常

### ISSUE THREAD

**Issue by yusensu** [fex-team/webuploader#1982]
如果同时上传多个文件，在上传的过程中，stop 或cancelFile某一个文件后，其他剩余的文件出现上传异常，并且即使重新刷新再传，也会出现上传文件异常！如果没有stop 或cancelFile文件，上传都是正常的。请问如何解决？

**Comment by yusensu** [comment]
已解决，单例模式问题

**Comment by songzeng2016** [comment]
请问怎么解决的，我现在遇到的问题是，选择多个文件上传，暂停某一文件后，其余的文件也不上传了
