### ISSUE TITLE
用flash上传在低版本IE或者火狐上传报406错误

### ISSUE THREAD

**Issue by a526672351** [fex-team/webuploader#1999]
错误原因是flash发送给后端是text/_类型，如果后端返回参数不对应类型直接给拒绝，望修复在flash上传的时候发送的头是_/*的类型，就能完美解决这个问题。

**Comment by a526672351** [comment]
要不的话，只能要后端配合来修改返回类型，后端会受限

**Comment by a526672351** [comment]
可以通过
uploader.on('uploadBeforeSend', function (obj, data, headers) {
            $.extend(headers, {
                Accept: "*/*"
            });
        });
设置解决

**Comment by asypost** [comment]
应该是：
uploader.on('uploadBeforeSend', function (obj, data, headers) {
$.extend(headers, {
Accept: **" * / * "**
});
});
设置解决
