### ISSUE TITLE
上传完成后获取PHP端返回数据问题！

### ISSUE THREAD

**Issue by tyua07** [fex-team/webuploader#202]
先展示我的代码：

前端上传成功代码：

![js](https://cloud.githubusercontent.com/assets/4219999/3088227/08c86598-e56b-11e3-9524-efcafdc6a36d.png)

后端代码：
![php](https://cloud.githubusercontent.com/assets/4219999/3088210/b35cec50-e56a-11e3-9953-afe39d2e1af5.png)

浏览器：
![json](https://cloud.githubusercontent.com/assets/4219999/3088229/0d8ae7e0-e56b-11e3-92db-cef7ec4d0d02.png)

**Comment by lxc939134342** [comment]
请问一下 php上传成功后 返回什么值给前台 才会提示上传成功了呢？

**Comment by dongyule** [comment]
建议参考server/fileupload.php的逻辑
