### ISSUE TITLE
请问如何指定使用flash？

### ISSUE THREAD

**Issue by FangDangWoNiu** [fex-team/webuploader#2027]
请问如何指定使用flash？

**Comment by exaho12** [comment]
在var uploader = WebUploader.Uploader({下可以声明
 runtimeOrder {Object} [可选] [默认值：html5,flash]
指定运行时启动顺序。默认会想尝试 html5 是否支持，如果支持则使用 html5, 否则则使用 flash.
可以将此值设置成 flash，来强制使用 flash 运行时。

**Comment by FangDangWoNiu** [comment]
@exaho12 谢谢啊，找APi的时候发现这个参数了
