### ISSUE TITLE
请问不设置pick属性，如何触发选择文件窗口呢

### ISSUE THREAD

**Issue by gdisk** [fex-team/webuploader#2059]
uploader = WebUploader.create({
                swf: ctx + '/framework/webuploader/Uploader.swf',
                server: 'http://webuploader.duapp.com/server/fileupload.php',
                resize: false,
                //pick:'#filebox'
            });
我不想用自带的按钮样式，想在点击自己的按钮时调用api，打开选择文件的窗口

**Comment by aihaiyue123** [comment]
朋友想出来了吗？我也想这样

**Comment by lixiaoyu** [comment]
请问解决了吗？好像用他们pick生成的按钮没办法更改样式
