### ISSUE TITLE
怎么获取单个图片的尺寸呢

### ISSUE THREAD

**Issue by ixxiyy** [fex-team/webuploader#2079]
uploader.on('beforeFileQueued',
            function (file) {
                console.log(file);
                console.log(file._info);
            });

输出 file 里面我看着有,但是获取不到

**Comment by heihei001** [comment]
我也想知道，我也需要获取图片尺寸，打印出来有但是用的时候是没有的，真是奇怪了。

**Comment by heihei001** [comment]
兄弟，我找到方法了。
首先让文件进入上传队列，
然后在上传队列中监听makeThumb把file传进去，然后在回掉函数中_info就幼稚了。

参考链接：
http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_makeThumb
