### ISSUE TITLE
如何实现跨域上传附件

### ISSUE THREAD

**Issue by AlbertKnag** [fex-team/webuploader#208]
在API中没有发现跨域上传附件的相关说明，请教如何实现跨域上传附件。jquery file upload有一个forceIframeTransport的参数，不知道webuploader是否有类似的参数。
查看了#135，由于我这边是上传附件到第三方系统，且上传URL是通过文件名自动生成，没办法从后端去解决，项目时间紧，希望能尽快回复

**Comment by StoneShowLee** [comment]
@AlbertKnag 请问你解决这个问题了吗？我现在也跟你一样，接入第三方系统跨域上传

**Comment by AlbertKnag** [comment]
@StoneShowLee 时间比较久远，已经记不得了，只知道后面功能完整实现了，整体功能是在一个邮件系统里面点一个上传按钮，然后把大附件上传到一个网盘系统里，跟QQ邮箱的文件中转站类似
