### ISSUE TITLE
图片上传button不能点击bug

### ISSUE THREAD

**Issue by hlerenow** [fex-team/webuploader#2118]
图片上传button，初始化设置样式为style:none,当页面加在完后，将button的样式设置为display:block，按钮不能点击，应该是webuploader生成的input的大小计算出错，input大小为 1x1 px，以致于点击不了，希望修复

**Comment by huangxiangsai** [comment]
@hlerenow 

## 首先

通过查看元素可以知道,webuploader并没有对input元素本身做宽高的计算设置

input只是用于触发文件选择框，即使input设置成了1x1也可以通过js过触发

## 其次

webuploader确实做了宽高的设置，这设置的宽高就是按钮的可点击区域，而这宽高，是由webuploader初始化前的载体元素决定的。

## 说到底

简单的说，还是按钮的样式问题，对于样式，webuploader貌似不会管的，也没必要管。

**Comment by hlerenow** [comment]
这个问题我已经解决了，的确是通过修改css样式解决的.我自己也查看了css样式，上传图片的button由三部分组成，一个是button的容器div，里面有一个input和lable,初始化时设置button的css为dispaly:none,，页面加载完成后设置button的css为display:block,此时容器的div会有个内联样式为1x1 px 按钮能正常显示，但是不能点击，也不能说不能点击，就是点击的区域太小了，以至于就像不能点击，然后正常的button却会有一个内联样式 widh:100%;height:100%;所以我觉得这应该js里面有设置这些样式，也不是说不能解决，只是突然出现这个问题，会觉得太奇怪而已。文档也没有说明，所在这里提一下

**Comment by huangxiangsai** [comment]
@hlerenow 
这种上传按钮不能点击的问题， 一般可能就是样式造成的。

但如果用的是flash模式，flash未成功加载也为点击无反应。

还可能flash成功加载，但如果初始化时按钮是隐藏的，而后显示出的上传按钮也可能会出现不可点击的情况。

**Comment by javaxiaobai** [comment]
在吗？楼主

**Comment by javaxiaobai** [comment]
解决
问题啊

**Comment by javaxiaobai** [comment]
在那个地方修改css样式？

**Comment by hlerenow** [comment]
随你在哪里修改样式，你只要在你的css文件里 把按钮的点击层（应该是button最外层的那个div，记不清了）样式的宽度和高度 设置大一点就行了
