### ISSUE TITLE
IE8下生成缩略图 尺寸大于110*110 就显示不完整

### ISSUE THREAD

**Issue by wang3156** [fex-team/webuploader#2120]
在IE8下 我需要上传base64的 所以 就想生成原图大小的缩略图 可是当图片大于110*110 时 就只显示大约1/3的图片 .其它内容都是空白的 ,例如原图 是下面这图这么大 缩略图后 尺寸还是设置 的设置 没问题.但是只有 红色框 那么大一块内容 其它的都是空白的 请问如何解决
![xxi2evr jk0rasou _rw_99](https://cloud.githubusercontent.com/assets/18094713/20392115/5ffe61bc-ad11-11e6-88e0-d360836e3a1e.png)

**Comment by Davis-HW** [comment]
请问你在IE8下是怎么使用的，为什么我在IE8下点击选择图片毫无反应，swf文件路径也配了flash也更新了，还是不行，快逼疯了。

**Comment by wang3156** [comment]
用的13.0的flash

**Comment by zzuzsj** [comment]
我能不能看一下你webuploader的配置

**Comment by wang3156** [comment]
配置是拷的dome里的那一块只是把缩略图大写改为了固定的500*300
