### ISSUE TITLE
一个页面，4个上传按钮，每个按钮需要上传不同的formData，请问如何点击不同的上传按钮，然后动态修改formData数据？

### ISSUE THREAD

**Issue by yuweiming2016** [fex-team/webuploader#2184]
一个页面，4个上传按钮，每个按钮需要上传不同的formData，请问如何点击不同的上传按钮，然后动态修改formData数据？

**Comment by yuweiming2016** [comment]
忘了一个事情，补充一下，我想代码简洁一点，只用一个webuploader实例，可以吗？

**Comment by will-always** [comment]
你好 你是怎样把配置的 我只要把文件名传到保存页面 看了半天没看懂

**Comment by yuweiming2016** [comment]
![image](https://cloud.githubusercontent.com/assets/22490427/21598742/dfe67ab8-d19c-11e6-9765-f624cf264f47.png)
四个按钮，每个按钮需要传一个不同的参数，我暂时还不知道怎么动态修改formData，，，
![image](https://cloud.githubusercontent.com/assets/22490427/21598763/436c4dd8-d19d-11e6-9ba7-20409433f171.png)
这里据说可以改formData，但这里如何判断是那个上传按钮，还搞不清楚

**Comment by yuweiming2016** [comment]
原文件名，如果后台用springmvc的话，直接可以获取，不用传
![image](https://cloud.githubusercontent.com/assets/22490427/21598787/96917cb8-d19d-11e6-8768-e038d6ba0052.png)

**Comment by will-always** [comment]
我都解决了 比如我们要传一个文件夹的id：
formData: {
                folderId: $("#folderId").val(),
                uid: 123
            },

**Comment by will-always** [comment]
又发现一个问题 请问怎么解决 改变相册的时候 相册Id始终没变化 默认第一个 请问怎么解决
<select class="select01" id="folderId">
    @foreach (var items in selectedData)
      {
        <option value="@items.Id">@items.Name</option>
      }
    </select><span class="warning"> *</span>@Html.ValidationMessage("folderId")
![01](https://cloud.githubusercontent.com/assets/24828177/26447291/7bf63414-417a-11e7-8a85-03ad77c819aa.png)
