### ISSUE TITLE
webuploader创建多个实例第一个能用后面的都用不了

### ISSUE THREAD

**Issue by stylefeng** [fex-team/webuploader#2227]
这个是我写的封装类

`/**
 * web-upload 工具类（只适用于上传一个图片）
 * 
 * 约定：
 * 上传按钮的id = 图片隐藏域id + 'BtnId'
 * 图片预览框的id = 图片隐藏域id + 'PreId'
 * 
 */
(function() {
	
	var $WebUpload = function(pictureId) {
		this.pictureId = pictureId;
		this.uploadBtnId = pictureId + "BtnId";
		this.uploadPreId = pictureId + "PreId";
		this.uploadUrl = Feng.ctxPath + '/user/upload';
		this.fileSizeLimit = 10 * 1024 * 1024;
		this.picWidth = 800;
		this.picHeight = 800;
	};

	$WebUpload.prototype = {
		/**
		 * 初始化webUploader
		 */
		init : function() {
			var uploader = this.create();
			this.bindEvent(uploader);
			return uploader;
		},
		
		/**
		 * 创建webuploader对象
		 */
		create : function() {
			var webUploader = WebUploader.create({
				auto : true,
				pick : {
					id : '#' + this.uploadBtnId,
					multiple : false,// 只上传一个
				},
				accept : {
					title : 'Images',
					extensions : 'gif,jpg,jpeg,bmp,png',
					mimeTypes : 'image/*'
				},
				swf : Feng.ctxPath
						+ '/static/css/plugins/webuploader/Uploader.swf',
				disableGlobalDnd : true,
				duplicate : true,
				server : this.uploadUrl,
				fileSingleSizeLimit : this.fileSizeLimit
			});
			
			return webUploader;
		},

		/**
		 * 绑定事件
		 */
		bindEvent : function(bindedObj) {
			var me =  this;
			bindedObj.on('fileQueued', function(file) {
				var $li = $('<div><img width="100px" height="100px"></div>');
				var $img = $li.find('img');

				$("#" + me.uploadPreId).html($li);

				// 生成缩略图
				bindedObj.makeThumb(file, function(error, src) {
					if (error) {
						$img.replaceWith('<span>不能预览</span>');
						return;
					}
					$img.attr('src', src);
				}, me.picWidth, me.picHeight);
			});

			// 文件上传过程中创建进度条实时显示。
			bindedObj.on('uploadProgress', function(file, percentage) {
			});

			// 文件上传成功，给item添加成功class, 用样式标记上传成功。
			bindedObj.on('uploadSuccess', function(file,response) {
				Feng.success("上传成功");
				$("#" + me.pictureId).val(response._raw);
			});

			// 文件上传失败，显示上传出错。
			bindedObj.on('uploadError', function(file) {
				Feng.error("上传失败");
			});

			// 其他错误
			bindedObj.on('error', function(type) {
				if ("Q_EXCEED_SIZE_LIMIT" == type) {
					Feng.error("文件大小超出了限制");
				} else if ("Q_TYPE_DENIED" == type) {
					Feng.error("文件类型不满足");
				} else if ("Q_EXCEED_NUM_LIMIT" == type) {
					Feng.error("上传数量超过限制");
				} else if ("F_DUPLICATE" == type) {
					Feng.error("图片选择重复");
				} else {
					Feng.error("上传过程中出错");
				}
			});

			// 完成上传完了，成功或者失败
			bindedObj.on('uploadComplete', function(file) {
			});
		}
	};

	window.$WebUpload = $WebUpload;
}());`

然后我实例化的时候是这样实例化

//初始化头像上传
var avatarUp = new $WebUpload("userAvatar");
avatarUp.init();
	
//初始化车辆图片上传
var vehicleImage = new $WebUpload("vehicleImage");
vehicleImage.init();
	
//初始化行驶本上传
var xszImage = new $WebUpload("xszImage");
xszImage.init();
	
//初始化驾驶证上传
var jszImage = new $WebUpload("jszImage");
jszImage.init();

html 中我是这么写的：
```

<div class="form-group">
	<label class="col-sm-3 control-label head-scu-label">头像</label>
	<div class="col-sm-4">
		<div id="userAvatarPreId"></div>
	</div>
	<div class="col-sm-2">
		<div class="head-scu-btn upload-btn" id="userAvatarBtnId">
			<i class="fa fa-upload"></i>&nbsp;上传
		</div>
	</div>
	<input type="hidden" id="userAvatar" />
</div>

```
但是我实例化完这4个webuploader只有第一个上传按钮管用，其他的都不管用
但是~！
奇怪的是，我把我的firefox浏览器窗口大小改变一下，其他三个按钮就都能用了，这是为啥？

**Comment by stylefeng** [comment]
问题已经解决，是我初始化页面的时候没有初始化html造成按钮不能用， 不是webuploaderd的问题，另外我封装的js经测试没有问题

**Comment by jooner888** [comment]
能否给个完整 的代码啊？

**Comment by mengqinWu** [comment]
为什么我是第一个可以上传图片就是点击再次覆盖时点击没反应，下面两个都是好的，具体是第一个实例只能选择图片一次，再次点击选择图片没反应，下面两个可以更换图片
![image](https://user-images.githubusercontent.com/19563091/27574287-43bddb78-5b48-11e7-8a87-ec5e36d557a8.png)

**Comment by mengqinWu** [comment]
不好意思，我知道了，我加了这个paste:document.body,，导致webuploader-container直接加到了body的身上，
![qq 20170627150215](https://user-images.githubusercontent.com/19563091/27574727-1f6158a2-5b4a-11e7-8baf-78601fdf9bd5.png)

**Comment by yexue098** [comment]
有没有实例的代码呢，想学习下

**Comment by zhanghongsheng000** [comment]
求demo发邮箱2417112386@qq.com 谢谢

**Comment by stylefeng** [comment]
在我的开源项目guns中用到了    可以关注一下  http://git.oschina.net/naan1993/guns

**Comment by zhouatie** [comment]
问题已经解决，是我初始化页面的时候没有初始化html造成按钮不能用， 不是webuploaderd的问题，另外我封装的js经测试没有问题

你好 这句话我没有明白您说的是什么意思，初始化html是什么意思

**Comment by sxbjy** [comment]
@zhouatie  应该是他的插件所在的父元素默认是隐藏的，改成默认显示就行了。。。。我用的setTimeout在文档加载完成后0.1秒把它隐藏了。
