### ISSUE TITLE
addBtn生成的样式无法覆盖按钮大小

### ISSUE THREAD

**Issue by jahentao** [fex-team/webuploader#2237]
当我尝试通过addBtn 再添加一个上传按钮的时候

默认产生的样式无法覆盖按钮大小
![image](https://cloud.githubusercontent.com/assets/15883913/22862401/9d6382f8-f168-11e6-9484-a45bb7121d85.png)

我的运行环境Win10, useragent : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 BIDUBrowser/8.4 Safari/537.36

**Comment by Suwings** [comment]
自己刚刚翻了下 WebUploader 的源码，看见refresh函数里面有刷新表单。
uploder.refresh() 即可重新刷新表单尺寸...
