### ISSUE TITLE
谷歌55.0.2883.87m上，打开很慢，大概等5秒左右~

### ISSUE THREAD

**Issue by Ryoui** [fex-team/webuploader#2261]
> accept: {
  title: 'Images',
  extensions: 'jpg,jpeg,png',
  mimeTypes: 'image/*'
}

> 
解决办法：改为

> accept: {
  title: 'Images',
  extensions: 'jpg,jpeg,png',
  mimeTypes: 'image/jpg,image/jpeg,image/png'   //修改这行
}

**Comment by xiaojiangang** [comment]
确实有这个问题。。。。 谷歌浏览器好像都这样。
