### ISSUE TITLE
在使用webUploader进行文件上传，使用IE11下的兼容模式IE9、IE8,在初始化webUploader对象时，出现SCRIPT5022: Runtime Error错误，请大神指教

### ISSUE THREAD

**Issue by dds521** [fex-team/webuploader#2270]
![image](https://cloud.githubusercontent.com/assets/26084117/23400129/d895da70-fddd-11e6-9445-e4af9e1a87b3.png)

**Comment by dds521** [comment]
哈哈

**Comment by dds521** [comment]
首先判断是否有Flash插件，如果没有进行下载（基本上都有的）
其次查看Flash是否注册成功：
     在命令提示符中输入以下命令：
            32位系统： 先输入 cd C:\Windows\System32\Macromed\Flash 后按下回车键
              再输入 regsvr32 Flash.ocx 后按下回车键
           64位系统： 先输入 cd C:\Windows\SysWOW64\Macromed\Flash 后按下回车键 
             再输入 regsvr32 Flash.ocx 后按下回车键。
基本上就可以了。
出现这种情况的原因可能是系统是盗版的导致FLash插件没有被注册。

**Comment by 5201314999** [comment]
有用
