### ISSUE TITLE
如何获取图片的宽度和高度？

### ISSUE THREAD

**Issue by shicongbuct** [fex-team/webuploader#2283]
![1](https://cloud.githubusercontent.com/assets/16701631/23640654/0b5fd9a0-032a-11e7-93b9-89e405a56de7.png)

如图，打印出了这个对象，想获取_info中的图片的宽高，但是怎么也获取不到_info属性。

**Comment by yao978318542** [comment]
其实在 uploadProgress 方法中可以获取到 但这个时候图片已经上传到服务器了 stop也起不到作用了！创建进度条之前的方法 全都是能打印出来但是获取不到！

**Comment by shicongbuct** [comment]
问题已解决，通过缩略图完成了对图片大小的限制。
