### ISSUE TITLE
请问有只允许上传一张图片的功能吗？

### ISSUE THREAD

**Issue by Ryoui** [fex-team/webuploader#2301]
不是设置fileNumLimit为1的意思。先选择了一张图片后，发现选错了，重新选择一张替换前面一张，并把前面一张移除队列。队列中中保存最后一张。
我现在的做法是不设置fileNumLimit，然后移除缩略图样式并reset(),重置队列。不过这样点上传按钮后没反应，既不报错也不成功，触发了startUpload事件，但没触发uploadStart事件，求助....第一回使用webuploader，谢谢大神.

**Comment by yogalin1993** [comment]
请问如何移除缩略图？
