### ISSUE TITLE
为什么选择文件的窗口在谷歌里面打开的很慢啊，在IE9里面到是挺快的

### ISSUE THREAD

**Issue by xqs121** [fex-team/webuploader#2321]

**Comment by Arthassssss** [comment]
我也遇到这个问题了

**Comment by xqs121** [comment]
已经解决了

**Comment by MeiYuanChen** [comment]
请问是怎么解决的 能分享一下吗

**Comment by xqs121** [comment]
accept: {
			title: 'Images',
			extensions: 'gif,jpg,jpeg,bmp,png',
			mimeTypes: 'image/jpg,image/jpeg,image/png,image/bmp'
		},

**Comment by MeiYuanChen** [comment]
你支持的文件类型和我的对比好少啊 我是：
`extensions: 'doc,docx,pdf,bmp,jpg,jpeg,png,rar,zip'`
不知道怎么办才好

**Comment by SnailOwO** [comment]
这个貌似是chrome的一个BUG！我使用其他的上传插件也是这样,比如pupload
