### ISSUE TITLE
苹果手机上传图片时，直接打开了相机，无法选择相册里的图片。

### ISSUE THREAD

**Issue by soraly** [fex-team/webuploader#2333]
测试后发现只有最新版本的苹果（IOS10.3）有这个问题，10.2及以下没有。

**Comment by dongsongshan** [comment]
楼主的问题解决了吗？借楼同问

**Comment by soraly** [comment]
解决了，把input的camera属性删掉就行了，ios最新版会把这个属性默认为打开相机

**Comment by feimengv** [comment]
确实是解决了：input.attr( 'capture', 'camera');  把capture里面camera 去掉就可以了
