### ISSUE TITLE
获得上传文件的源路径

### ISSUE THREAD

**Issue by EzrealDeng** [fex-team/webuploader#2345]
如何获得我上传文件的源路径，选择文件后的file对象好像并没有这个属性

**Comment by 599316527** [comment]
> When a file is chosen using an <input type="file">, the real path to the source file is not shown in the input's value attribute for obvious security reasons. Instead, the filename is shown, with C:\fakepath\ appended to the beginning of it.

via. https://developer.mozilla.org/en/docs/Web/HTML/Element/input

**Comment by EzrealDeng** [comment]
In fact , I want to limit the image's size , if the image's width and height not match to my demands ,It can't be uploaded ,how should I do ?

**Comment by 599316527** [comment]
用 `URL.createObjectURL()` 创建 objectUrl 赋值给 img.src 然后通过 dom 接口取宽高，搜索一下很难么

https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images

**Comment by Wifiwx** [comment]
我也想获取上传的文件所属的文件夹名，   拿不到。。。。。。
