### ISSUE TITLE
Ueditor 里面为什么会报http请求错误？

### ISSUE THREAD

**Issue by rujianwang** [fex-team/webuploader#238]
我的环境是：
1、http://a.abc.com  (ueditor的页面  [1.4.3 .Net 版本])
2、serverUrl:http://file.abc.com/ueditor/net/controller.ashx 
3、服务器端crossdomain.xml
<?xml version="1.0" encoding="utf-8" ?>
<cross-domain-policy>
  <allow-access-from domain="*.abc.com"/>
</cross-domain-policy>
4、images.js 中 开启了flash上传： runtimeOrder: 'flash',

**Comment by th-520** [comment]
@2betop flash的跨域上传，在谷歌上是正常的，在ie和火狐都是不行，都报错http
![default](https://cloud.githubusercontent.com/assets/20639456/18614703/6d9d9204-7dc6-11e6-964c-1c27bb1078eb.png)
cossdomain.xml文件内容也是正确的，这是为啥呢？
