### ISSUE TITLE
MD5值计算不正确

### ISSUE THREAD

**Issue by only-gale** [fex-team/webuploader#2436]
我有一张jpg图片，在上传之前要计算md5值，但奇怪的是，第一次计算出来的值是错误的，紧接着重试上传所计算出来的md5值就是正确的，这是为什么？求助！

第一次计算出的值为0bd24e4d3f093d93c8a0493713d8213a，第二次计算出的值为6daa4965213822c9aa185fd76ca28287。
![default](https://cloud.githubusercontent.com/assets/3478864/26478621/0f053b30-4200-11e7-8105-02aa88d6e599.jpg)

**Comment by alongchengtian0** [comment]
可以查看文档，找一下相关问题
[常见问题](https://alongchengtian0.gitbooks.io/webuploader/content/)
@only-gale

**Comment by only-gale** [comment]
@alongchengtian0 终于找到了蛛丝马迹，是因为在pre-upload计算md5的时候图片未压缩，但是upload的时候却有默认压缩，导致后台计算的md5值和前端计算的md5值不符。我取消webuploader的压缩行为就好了。
