### ISSUE TITLE
请问大家，上传文件时（不是上传文件前）怎么传文件md5进入接口中？

### ISSUE THREAD

**Issue by yeqingyun** [fex-team/webuploader#2437]
uploader = WebUploader.create({
		    swf: swfUrl,  
		    server: hostUrl+"chunkFileUpload.html",
		    chunked: true,
		    chunkSize: !!chunkSize?chunkSize:10*1024*1024,
		    pick: { id:'#'+filePickerDiv,multiple:!!!isMultiple?isMultiple:true},
		    resize: false
		});

我能够在before-send之前这样改吗 uploader .server = hostUrl+"chunkFileUpload.html?filemd5"+ block.file.md5;
这样可行吗？

**Comment by alongchengtian0** [comment]
可以查看文档，找一下相关问题
[常见问题](https://alongchengtian0.gitbooks.io/webuploader/content/)

**Comment by yeqingyun** [comment]
@alongchengtian0 谢谢，帮大忙了！
