### ISSUE TITLE
bootstrap下modal中，按钮初始化后，无法点击的问题

### ISSUE THREAD

**Issue by sesamefly** [fex-team/webuploader#2446]
应该是modal显示时，尚未获取到高度，导致file标签高度和宽度为1导致的。

**Comment by boomgpd** [comment]
恩恩，这个问题怎么解决的呢，求告知，

**Comment by boomgpd** [comment]
具体如下：

  $(function () {
        var _$modal = $(‘#MyModal‘);
        _$modal.css(‘display‘, ‘block‘);
        _$modal.addClass("webuploader-element-invisible");
 
        var uploader = WebUploader.create(...);
 
        _$modal.on(‘show.bs.modal‘, function () {
            _$modal.removeClass("webuploader-element-invisible");
        });
    });
 
在实例化webuploader前后设置模态框的display属性，来解决模态框加载前，webuploader无法获取模态框高度，导致其设置file标签宽、高度异常（为1），从而无法触发其点击事件的问题。
