### ISSUE TITLE
请问大家图片上传后md5值和上传之前不一样，怎么解决

### ISSUE THREAD

**Issue by yeqingyun** [fex-team/webuploader#2449]
uploader = WebUploader.create({
            swf: swfUrl,
            server: hostUrl,
            chunked: true,
            chunkSize: !!chunkSize ? chunkSize : 50 * 1024 * 1024,
            pick: {id: '#' + filePickerDiv, multiple: !!!isMultiple ? isMultiple : true},
            resize: false,
            method: 'POST'
        });

其他文件正常，图片上传后md5值和上传之前不一样了，难道webUpload压缩了图片吗，请问怎么图片让md5不变

**Comment by yeqingyun** [comment]
图片长度也变化了，
compress ：{
    width: 1600,
    height: 1600,

    // 图片质量，只有type为`image/jpeg`的时候才有效。
    quality: 90,

    // 是否允许放大，如果想要生成小图的时候不失真，此选项应该设置为false.
    allowMagnify: false,

    // 是否允许裁剪。
    crop: false,

    // 是否保留头部meta信息。
    preserveHeaders: true,

    // 如果发现压缩后文件大小比原来还大，则使用原来图片
    // 此属性可能会影响图片自动纠正功能
    noCompressIfLarger: false,

    // 单位字节，如果图片大小小于此值，不会采用压缩。
    compressSize: 20*1024*1024
}之后md5不变了，但是长度仍然变化了

**Comment by cdswyda** [comment]
你都压缩了 肯定会变啊
