### ISSUE TITLE
进度条问题

### ISSUE THREAD

**Issue by fengyundong22** [fex-team/webuploader#2457]
暂停后继续上传的文件进度条从0开始，怎样改成从暂停时的进度开始？

**Comment by asimplepeople** [comment]
同求

**Comment by fengyundong22** [comment]
修改js里的暂停部分

**Comment by asimplepeople** [comment]
//uploader.upload(uploader.getFiles("interrupt")); //如果用这个的话上传进度会归0
                                uploader.upload(); //使用下面的继续上传不会归0
