### ISSUE TITLE
再次进入页面的时候想让之前上传的文件显示在队列中

### ISSUE THREAD

**Issue by ljingz** [fex-team/webuploader#249]
文件上传成功了，然后再次进入页面的时候想让之前上传的文件显示在队列中，请问我要如何触发fileQueued事件，还有如何创建文件对象，还是有其他方法，谢谢。

**Comment by kevinfszu** [comment]
问题是，如果不重建队列，后端渲染出文件列表之后，webuploader 的文件数量限制功能就懵逼了，无法识别已经后端渲染出来的已经存在的文件。
