### ISSUE TITLE
why not support npm while node.js is popular?

### ISSUE THREAD

**Issue by pyz1989** [fex-team/webuploader#2525]
I think it is time to support npm install.

**Comment by IShinji** [comment]
https://www.npmjs.com/package/webuploader

**Comment by pyz1989** [comment]
好的，谢谢
官网：http://fex.baidu.com/webuploader/download.html
**下载**里面没有写如何npm安装，下载方式写的只有打包版本、cdn版本、Git项目包这3种，还以为不支持npm
