### ISSUE TITLE
小白问题：点击开始上传没有反应，该如何绑定开始上传事件？

### ISSUE THREAD

**Issue by nkshuangyuan** [fex-team/webuploader#2528]
var uploader = WebUploader.create({
  	    // swf文件路径
  	    swf: '<%=path%>/framework/webupload/Uploader.swf',
  	    // 文件接收服务端。
  	    server: baseUrl + '/pano/upload',
  	    // 选择文件的按钮。可选。
  	    // 内部根据当前运行是创建，可能是input元素，也可能是flash.
  	    pick: '#picker',
  	    // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
  	    resize: false
  	});
找不到开始上传按钮点击事件的配置啊

**Comment by IShinji** [comment]
// 选择文件的按钮。可选。
// 内部根据当前运行是创建，可能是input元素，也可能是flash.
pick: '#picker',
这个不就是么……

**Comment by nkshuangyuan** [comment]
找到了，还是没有仔细看官方文档。。要用uploader的upload方法。
我配置的是不自动上传，自己点击提交按钮一起上传，应该是这样
`
$("#ctlBtn").click(function(){
  		uploader.upload();
  	});
`
