### ISSUE TITLE
分块上传到OSS，如何接收“Response Headers”中的“ETag”？

### ISSUE THREAD

**Issue by YoungSx** [fex-team/webuploader#2532]
比如我用百度BOS的分块上传，上传完每一分块，在请求返回的 Response Headers 中有一个 “ETag”参数，用来标志每一块，以便最后合并分块。
可是我在 WebUploader 中却无法获取到 每一个分块上传结束后的 Response Headers，请问有解吗？

**Comment by YoungSx** [comment]
我在 “uploadAccept” 事件的“object”中并没有找到相关的东西，而且"ret"是空的。
可是在F12 Network中能看到 response headers

**Comment by 2betop** [comment]
Flash 读取不到，html 5 的版本可以提供

**Comment by YoungSx** [comment]
@2betop 好的，只需要 HTML5 版本的，谢谢~

**Comment by 2betop** [comment]
现在最新的 dist 目录已经支持了

**Comment by YoungSx** [comment]
@shangwq 如果是为了 Etag 的话已经不需要 Response Headers 了，因为 Etag 在现在的版本中已经被保存下来了。

**Comment by shangwq** [comment]
@YoungSx 忘记说了，我的是阿里的OSS，是必须读header的，我用的是dist里面的最新版，读取到的是空值。你用的webuploader最新版能读取到header信息吗

**Comment by YoungSx** [comment]
@2betop 我知道，Etag 在 Response Headers 中，我用的 COS 和 BOS 也差不多，但是 WebUploader 已经帮你读好存下来了，不用再去 Response Headers 里面找了。具体存哪里我记不清了，你 Console.log 一下文件对象看看。
