### ISSUE TITLE
选择图片不想上传或者上传成功后，怎么删除图片

### ISSUE THREAD

**Issue by huangchaofei** [fex-team/webuploader#2545]
如题，添加一个按钮吗 然后附带点击事件？

**Comment by LouisYis** [comment]
file.on('statuschange', function (cur, prev) {
            if (prev === 'progress') {
                $prgress.hide().width(0);
            } else if (prev === 'queued') {
                //上传js里面，注释掉这两行，就有了
                //$li.off('mouseenter mouseleave');
                //$btns.remove();
            }
