### ISSUE TITLE
如何限制无后缀文件的上传

### ISSUE THREAD

**Issue by zgfang1993** [fex-team/webuploader#2551]
- 我的配置

```
{
    title: 'File',
    extensions: 'txt',
    mimeTypes: 'text/plain'
}
{
   title: 'Images',
    extensions: 'jpg,jpeg,png',
    mimeTypes: 'image/jpg,image/jpeg,image/png'
}
```
上面分别是上传txt 和 图片的 配置，但是都能上传没有后缀的文件
![image](https://user-images.githubusercontent.com/14739234/29301411-8b430e78-81ae-11e7-8aee-e713fb79401d.png)

图片的只要在弹框选择所有文件，就可以传没有后缀的文件了。
![image](https://user-images.githubusercontent.com/14739234/29301255-7b2170bc-81ad-11e7-915c-9a94ce8538e8.png)

- 官网demo
以下是官方的demo，似乎也没有做限制
![image](https://user-images.githubusercontent.com/14739234/29301356-2139fa46-81ae-11e7-9177-a7ef508cd166.png)

**Comment by cobish** [comment]
@zgfang1993 请问，后来怎么解决的？

**Comment by LSL1618** [comment]
通过文件名去检验后缀
