### ISSUE TITLE
removeFile()方法没有生效

### ISSUE THREAD

**Issue by Feel-Joy** [fex-team/webuploader#2592]
代码如下
```js
// 初始化Web Uploader
    var uploader = WebUploader.create({

      // 选完文件后，是否自动上传。
      auto: false,

      // 文件接收服务端。
      server: 'http://webuploader.duapp.com/server/fileupload.php',

      // 选择文件的按钮。可选。
      // 内部根据当前运行是创建，可能是input元素，也可能是flash.
      pick: '#file-picker',

      // 只允许选择图片文件。
      accept: {
        title: 'Images',
        extensions: 'gif,jpg,jpeg,bmp,png',
        mimeTypes: 'image/*'
      }
    });

    // 当有文件添加进来的时候
    uploader.onFileQueued = function (file) {
      var $li = $(
        '<div id="' + file.id + '" class="file-item thumbnail">' +
        '<img />' +
        '</div>'
        ),
        $cancel = $('<span class="cancel"></span>'),
        $img = $li.find('img');

      $li.append($cancel)

      // $list为容器jQuery实例
      $('#photo-list').append($li);

      $li.on('click', function () {
        uploader.removeFile(file, true)
      })

      // 创建缩略图
      uploader.makeThumb(file, function (error, src) {
        if (error) {
          $img.replaceWith('<span>不能预览</span>');
          return;
        }

        $img.attr('src', src);
      }, 100, 100);
    };

    // 文件上传失败，显示上传出错。
    uploader.on('uploadError', function (file) {
      var $li = $('#' + file.id),
        $error = $li.find('div.error');

      // 避免重复创建
      if (!$error.length) {
        $error = $('<div class="error"></div>').appendTo($li);
      }

      $error.text('上传失败');
    });

    // 完成上传完了，成功或者失败，先删除进度条。
    uploader.on('uploadComplete', function (file) {
      $('#' + file.id).find('.progress').remove();
    });
```
添加是没有问题的，但是没办法删除已添加的图片，控制台没有报错，什么反应都没有。。。

**Comment by inkroom** [comment]
me too

**Comment by inkroom** [comment]
查看源码后发现原因，在2074行，是队列的removeFile方法，该方法只删除了存放在_map里的file。没有删除_queue里的file，修改一下即可

**Comment by Feel-Joy** [comment]
@inkroom [WbpUploader API](http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_removeFile) 中提到可以给 removeFile()添加第二个参数，为 true 会删除_queue里的file，在[b5461e](https://github.com/fex-team/webuploader/commit/b5461ee16deece92dbb34d2253f4c6ab3b215c1d)中已经修复了

**Comment by Feel-Joy** [comment]
@inkroom 我看了下，触发removeFile之后，_queue的length是减少了的，但是对应的页面元素却没有删掉，你知道哪里出问题了么？

**Comment by Feel-Joy** [comment]
已解决

**Comment by wangyushuai** [comment]
` simple_upload.on('uploadError', function (file) {
        console.log("上传失败，请重新上传！");
         simple_upload.removeFile(file，true);
    });`
您好，我也遇到类似的问题，上传失败之后，想删除图片，但是页面图片元素仍然存在，请问您知道原因吗

**Comment by inkroom** [comment]
> `simple_upload.on('uploadError', function (file) { console.log("上传失败，请重新上传！"); simple_upload.removeFile(file，true); });`
> 您好，我也遇到类似的问题，上传失败之后，想删除图片，但是页面图片元素仍然存在，请问您知道原因吗

页面图片元素仍然存在是什么意思？这个图片元素是怎么来的？webUploader生成的还是你自己创建的？删除图片之后webUpload里面的数据是否还在？

**Comment by wangyushuai** [comment]
> > `simple_upload.on('uploadError', function (file) { console.log("上传失败，请重新上传！"); simple_upload.removeFile(file，true); });`
> > 您好，我也遇到类似的问题，上传失败之后，想删除图片，但是页面图片元素仍然存在，请问您知道原因吗
> 
> 页面图片元素仍然存在是什么意思？这个图片元素是怎么来的？webUploader生成的还是你自己创建的？删除图片之后webUpload里面的数据是否还在？

监听了队列事件（fileQueued）：会将图片放到 $list里，。上传失败后，我想通过 removeFile方法移除 $list 里的图片，但是没有生效。 我看官网的demo 也是这样removeFile这样写的。

**Comment by inkroom** [comment]
@wangyushuai [$list是你自己维护的数据？你调用了removeFiile之后再调用getFiles数量没有变化？uploader里的文件是分状态的，你去[http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_getFiles](http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_getFiles)
看，getFiles方法是可以传参的；你删除的这个文件可能只是状态变了，并没有从队列中删除

**Comment by wangyushuai** [comment]
> @inkroom [WbpUploader API](http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_removeFile) 中提到可以给 removeFile()添加第二个参数，为 true 会删除_queue里的file，在[b5461e](https://github.com/fex-team/webuploader/commit/b5461ee16deece92dbb34d2253f4c6ab3b215c1d)中已经修复了

方便发下您写的 RemoveFile方法的调用吗，我写的怎么没起作用呢

**Comment by inkroom** [comment]
@wangyushuai 你可以这样来调试一下，先添加一个文件，调用getFiles()，看返回的文件的各个状态位，然后调用removeFiles(file)；再getFiles()，比较一下看有什么不同，最后在removeFile(file,true)，看文件是否被删除

**Comment by wangyushuai** [comment]
> @wangyushuai 你可以这样来调试一下，先添加一个文件，调用getFiles()，看返回的文件的各个状态位，然后调用removeFiles(file)；再getFiles()，比较一下看有什么不同，最后在removeFile(file,true)，看文件是否被删除

好的，谢谢您，我找到了原因了。上传图片时，创建的预览图片的html时需要自己手动remove的，removeFile可能只是清楚了队列中的数据，并不会清楚手动创建的HTML。
