### ISSUE TITLE
新建一个空的txt文件，上传提示类型错误，有内容的可以上传

### ISSUE THREAD

**Issue by amorous** [fex-team/webuploader#2607]
新建一个空的txt文件，上传提示类型错误，有内容的可以上传

**Comment by christingliu** [comment]
if ( !me.acceptFile( file ) ) {
                    me.owner.trigger( 'error', 'Q_TYPE_DENIED', file );
                    return;
                }
acceptFile: function( file ) {
                var invalid = !file || !file.size || this.accept &&

                        // 如果名字中有后缀，才做后缀白名单处理。
                        rExt.exec( file.name ) && !this.accept.test( file.name );

                return !invalid;
            }
webuploader.js里面对于file.size的大小做了判断。这个可以在beforeFileQueued的handler里面进行file.size大小的判断 出现提示 另外就是不仅仅限于空的txt文件 。空的其它类型文件也是无法进行上传的。
