### ISSUE TITLE
webuploader在部分ie8下无效,如图

### ISSUE THREAD

**Issue by x-a** [fex-team/webuploader#2667]
下面是两个按钮代码:
```
<div class="picker1 uploadPlaceholder1">上传附件</div>
<div class="picker1 uploadPlaceholder2">上传正文</div>
```

下面是实例化的部分代码:
`pick: ".picker1",`

正常来说实例化成功应该是下面这样
![fcgimv skihz3z 99 f 36](https://user-images.githubusercontent.com/12967276/32036237-1796a274-ba51-11e7-99f1-95b4bad3628d.png)

但在部分ie8下却没有实例化成功,如下图
![2y gd9og 55b0 kz txcu 2](https://user-images.githubusercontent.com/12967276/32036300-928b34d6-ba51-11e7-98e9-f209e93117aa.png)

这个问题如何解决呢??

**Comment by x-a** [comment]
只有一部分ie8不行, 我自己这边有两台ie8和一台ie7都可以, 但是有些客户的ie8死活就是不行, 不知道什么原因

**Comment by x-a** [comment]
解决了, 是因为没有安装flash的问题...

**Comment by designCoder110** [comment]
能帮我看看不，我所有的IE都不行，flash我也安装了
