### ISSUE TITLE
如何获取当前上传文件的速度？

### ISSUE THREAD

**Issue by tongliaozhang** [fex-team/webuploader#2691]
uploadProgress 事件中，我想获取当前上传文件的速度，这个应该怎么做？

**Comment by anrananran** [comment]
通过progress可以获取两次触发之间的差值，比如0.02%，同时可以另外计算出时间的差值，然后用0.02%乘以总文件大小再除以时间就能得到了

**Comment by tongliaozhang** [comment]
@anrananran 谢谢 我对这个插件理解的不够深，用你的方法已经基本实现了
