### ISSUE TITLE
上传失败通过uploadError的reason获取到的是http-

### ISSUE THREAD

**Issue by tankilo** [fex-team/webuploader#2705]
想获取到上传失败的http status,  搜索以后发现已经有commit [add http status on error code](https://github.com/fex-team/webuploader/commit/2af8e9b9a01ebc39460e97aedcab00689eb5a4ba) 修复这个问题。

但是发现最新版本的0.1.5里都没有包含这个修改，奇怪的是主分支版本开头已经是0.1.7-alpha
使用主分支dist目录的js文件测试发现
![image](https://user-images.githubusercontent.com/10413284/33534850-22cdbe72-d8e5-11e7-9123-0f2b256a84ff.png)

![image](https://user-images.githubusercontent.com/10413284/33534834-067d64b6-d8e5-11e7-9cda-ea783c1885ff.png)

**Comment by WPG** [comment]
#2687
