### ISSUE TITLE
ie9点击上传按钮没有反应，谷歌浏览器下使用flash可以正常上传

### ISSUE THREAD

**Issue by fan-lv** [fex-team/webuploader#2722]
1.GitHub上面下载的代码运行示例examples->image-upload在ie9下点击上传按钮没有反应，控制台查看flash插件已经加载。http://fex.baidu.com/webuploader/demo.html在线的demo可以在ie9下点击。
2.配置项设置runtimeOrder: 'flash',时谷歌浏览器可以上传文件。

**Comment by fan-lv** [comment]
原因是加载了两次flash，还不知道为什么会加载两次，排查中

**Comment by IEfucker** [comment]
麻烦说下是什么原因，怎么解决的
