### ISSUE TITLE
关于服务器端返回值的问题

### ISSUE THREAD

**Issue by mydirector** [fex-team/webuploader#280]
看了提供的fileupload.php，是否返回值只能是{"jsonrpc":"2.0","result":null,"id":"id"}，或者那个错误信息，我想自定义一些返回值，是否可以，比如{"jsonrpc":"2.0","result":null,"id":"id","imgurl":"url"}，我在前台如何读取这个返回值中的imgurl呢？

**Comment by izhangzhihao** [comment]
你好，你解决了吗，我看了半天文档，依然没找打解决办法！！！
