### ISSUE TITLE
请问webuploader实例怎么动态创建？就是在我点击某个按钮的时候把它创建出来

### ISSUE THREAD

**Issue by axu6705** [fex-team/webuploader#281]
请问webuploader实例怎么动态创建？就是在我点击某个按钮的时候把它创建出来，因为上传按钮是动态生成的，所以需要在生成之后动态创建一个webuploader实例

**Comment by yanziyanzi115** [comment]
你好，最近我也遇到了这个问题，请教下你之前是怎么解决的

**Comment by liunianyon** [comment]
@axu6705 能贴下解决方案吗，新手

**Comment by wengAlan** [comment]
如果有的弹窗到最后还是没实现，可以使用模拟点击来实现@liunianyong

**Comment by kk-fan** [comment]
> 如果有的弹窗到最后还是没实现，可以使用模拟点击来实现@liunianyong
模拟点击在flash模式下请问怎么实现？
