### ISSUE TITLE
请问我按照getting start写的    服务器端使用j2ee写的，但是服务器读取不到文件信息，就连文件名字都找不到，请问，这个对服务器语言有要求吗？

### ISSUE THREAD

**Issue by wengjohn** [fex-team/webuploader#283]

**Comment by LSL1618** [comment]
我用的spring mvc可以取到上传文件，但是取不到参数，
前端参数定义<==>formData : { subId : "e1f48d3297c44645867b4a1d07032d50" }，
后端参数获取<==>String subId = request.getParameter("subId")，
结果取出来的值为null。
后端到底应该怎么取参数？

**Comment by sky20054122** [comment]
@LSL1618  
~~~javascript
 MultipartHttpServletRequest mutilrequest = (MultipartHttpServletRequest) request; //转换request后，就可以获取了
  String chunkMd5 = request.getParameter("chunkMd5");
                Integer chunk = Integer.parseInt(request.getParameter("chunk"));
                Integer chunks = Integer.parseInt(request.getParameter("chunks"));
~~~

**Comment by Moving521** [comment]
官网的Demo都传不到后台方法里面。
后台log是：Log4j:[2016-03-30 18:06:32]  WARN DefaultHandlerExceptionResolver:189 - Handler execution resulted in exception: Content type 'multipart/form-data;boundary=----WebKitFormBoundaryDyb2jmqWBxekvNZ0;charset=UTF-8' not supported

前台报错：POST http://localhost:8080/phcloud-admin/dataSubmarket/updataContactExcelFields 415 (Unsupported Media Type)，
提示webloader.js的xhr.overMimeType()出问题！

**Comment by LSL1618** [comment]
@Moving521 ，前台报不支持的媒体类型，你传的什么文件？还有后台日志报什么错？
