### ISSUE TITLE
上传文件时，network中的请求参数有问题

### ISSUE THREAD

**Issue by chebysheph** [fex-team/webuploader#2861]
如题，上传文件的时候，options中fileVal为“package”，请求后network中的请求参数不仅有package字段，还多了id, name, type, lastModifiedDate, size等字段，为什么？这些多余的字段怎样去掉呢？

**Comment by Tianhg** [comment]
我也遇到了这个问题，楼主怎么解决的，能分享下不

**Comment by chebysheph** [comment]
并没有解决，多余的参数后台可以选择不接收，大概只能如此了

**Comment by LSL1618** [comment]
@chebysheph ，多余参数不会干扰后台就好。

**Comment by fengxingaotian** [comment]
不是说不接受就能可以的，这里面的问题是默认参数名占据了关键字段名，如果你加的参数和这些参数重名会遇到你后台接收的参数错误

**Comment by LSL1618** [comment]
@fengxingaotian ，后台接收参数的方式多种多样，可以换嘛。
