### ISSUE TITLE
如何获取上传队列中真正的文件个数

### ISSUE THREAD

**Issue by goodLuck-hui** [fex-team/webuploader#2930]
只允许上传9个文件，添加完九个文件之后，让上传按钮隐藏，当删除某个文件之后，判断真正存在队列的个数是不是9个，然后判断上传按钮显示与否。删除文件的时候调用了removeFile(id,true), uploader.getFiles()的文件个数依旧没有变化,请问大神们都怎么解决的呀

**Comment by PrintingChen** [comment]
您好，我也是弄多文件后台上传遇到了问题，请问您解决了吗？

**Comment by goodLuck-hui** [comment]
> 您好，我也是弄多文件后台上传遇到了问题，请问您解决了吗？

@PrintingChen uploader.getStats().successNum - uploader.getStats().cancelNum,可以获取到真正上传的格数，但是有一个问题就是fileQueued事件的中这样并不可以判断上传按钮是否隐藏，

**Comment by goodLuck-hui** [comment]
已解决，可以使用uploader.getFiles().length  - uploader.getStats().cancelNum
