### ISSUE TITLE
如何在外部捕获addFile事件

### ISSUE THREAD

**Issue by goodLuck-hui** [fex-team/webuploader#2932]
上传文件的时候，如果设置了fileNumLimit限制文件上传数量，如果选择的文件数量超过了fileNumLimit，会自动截取fileNumLimit个数量上传，其余的自动就过滤掉了。如何实现当选择的文件数量超过fileNumLimit时不上传，而是提示数量超出

**Comment by LSL1618** [comment]
把选完文件自动上传设置为false，再通过下边的事件判断一次性选择的文件数量，超出则清空上传队列。
```
uploader.on('filesQueued', function(files) {
       console.info("[filesQueued]");
});
```
仅供参考。

**Comment by goodLuck-hui** [comment]
@LSL1618 好的，谢谢了
