### ISSUE TITLE
上传新文件一直处于等待上传的问题

### ISSUE THREAD

**Issue by bakalr** [fex-team/webuploader#2947]
遇到一个问题，如果上传的都是不存在的新文件，此时是正常的；而如果再次上传一个已经上传过得存在的文件，会显示已上传，再传新文件或已存在文件就会显示等待上传，并一直不改变，请教这是什么原因呢

**Comment by LSL1618** [comment]
自己先debug找找原因

**Comment by bakalr** [comment]
已解决

**Comment by YCait** [comment]
@bakalr 你好，请问一下你怎么解决的呢，现在我也遇到了这个问题。
