### ISSUE TITLE
文件选择按钮、继续添加按钮等文字显示乱码！

### ISSUE THREAD

**Issue by lishu1108** [fex-team/webuploader#2959]
`// 添加“添加文件”的按钮，
        uploader.addButton({
            id: '#filePicker2',
            innerHTML: '继续添加'
        });`
`pick: {
                id: '#filePicker',
                innerHTML: '点击选择图片'
            },`
**配置无误，显示到网页上的文字乱码，是怎么回事？**

**Comment by LSL1618** [comment]
编码不统一吧

**Comment by lishu1108** [comment]
文件编码问题。
