### ISSUE TITLE
手机拍照后无法上传

### ISSUE THREAD

**Issue by myperworld** [fex-team/webuploader#299]
现在手机网页端上传是个需要打通的环节，经测试，该插件可以从手机相册选择图片上传，但是如果选择摄像头拍照，然后再上传，页面就莫名刷新了，无法上传了。

**Comment by hanwenbo** [comment]
ios  总是自动刷新呢？

**Comment by pineappleok** [comment]
也碰到上传就刷新，需求是要拍几张上传的，怎么实现。
