### ISSUE TITLE
0.1.5版本，ie8、ie9点击上传按钮无响应，flash版本足够高

### ISSUE THREAD

**Issue by ningwenfei** [fex-team/webuploader#3009]
![image](https://user-images.githubusercontent.com/26561341/58793326-77e7bb00-8628-11e9-8f77-5ff76e704412.png) 这是我在ie8里面右击截图

**Comment by heimasi** [comment]
解决了吗

**Comment by ningwenfei** [comment]
> 解决了吗

已解决

**Comment by ZYsoftkitty** [comment]
怎么解决的？

**Comment by onism68** [comment]
@ZYsoftkitty 配置ng看看swf后缀
