### ISSUE TITLE
请问如何在初始化后改变最大上传文件限制数，或者如何将上传文件数count带进去？

### ISSUE THREAD

**Issue by TaoJack624** [fex-team/webuploader#315]
*/
        api.addValidator( 'fileNumLimit', function() {
            var uploader = this,
                opts = uploader.options,
                count = 0,
                max = opts.fileNumLimit >> 0,
                flag = true;
即上面源码里的count如何在初始化后，不经过上传文件的方式改变count的值？或者如何在初始化后重置fileNumLimit的值？希望楼主帮忙，问题小白，望不吝赐教

**Comment by jl1014171068** [comment]
请问楼主最后如何解决的呢？我现在遇到的需求时编辑图片页面，在外围删除时如何触发内部验证的count更新呢？
