### ISSUE TITLE
webuploader 使用的二个问题

### ISSUE THREAD

**Issue by christopy-dev** [fex-team/webuploader#3156]
1、使用 removeFile( id, true ) 移除文件，但是getFiles() 方法还可以获取到移除的文件，请问这个移除的方法有效么？
![image](https://user-images.githubusercontent.com/36065190/102602422-7c1cf000-415c-11eb-9c1d-ab9f16640fca.png)

2、api中说uploadAccept 这个事件返回false，会触发uploadError事件，但我实际使用中，它并不会触发uploadError事件
![image](https://user-images.githubusercontent.com/36065190/102602233-306a4680-415c-11eb-90e5-b3a41312e7c6.png)

**Comment by nickname-sb** [comment]
第二个问题在 #361解决。

**Comment by christopy-dev** [comment]
已经解决
