### ISSUE TITLE
断点续传，某一片上传之前的监听事件的问题

### ISSUE THREAD

**Issue by AnAloneJaver** [fex-team/webuploader#3160]
项目中使用了断点续传，在某一片上传之前会通过一个before-send的监听事件来确定此片是否已经上传过。代码如下：
`
WebUploader.Uploader.register({
			"before-send" : "beforeSend"
		}, {
			"beforeSend" : function(block) {
				var deferred = WebUploader.Deferred();
				var file = block.file;
				var fileMd5 = file.wholeMd5;
				// 修改data可以控制发送哪些携带数据。
				$.ajax({
					type : "POST",
					url : obj.checkChunkPath,
					data : {
						token : uploader.options.formData.token,
						//文件唯一标记
						fileMd5 : fileMd5,
						//当前分块下标
						chunk : block.chunk,
						//当前分块大小
						chunkSize : block.end - block.start
					},
					dataType : "json",
					success : function(data) {
						if (data.isexist == 1) {
							//分块存在，跳过
							deferred.reject();
						} else {
							//分块不存在或不完整，重新发送该分块内容
							deferred.resolve();
						}
					}
				});
				return deferred.promise();
			}
		});
`

当页面中只有一个文件上传时，此文件有用，并没有其他问题。
问题描述：
  当页面中有其他文件上传时(也使用webuploader)，此监听同样生效与其他上传，
ex：
 文件1：大文件上传 (需要分片和断点续传)
 文件2：图片上传(不需要分片和断点续传)

文件1需要上面的伪代码，文件2不需要。但是实际情况当我再上传文件2的时候，仍然会被上面的监听事件监听到。

请问下，这个情况应该如何解决呢？或者说如何让这个监听只监听某一个文件上传呢？
（ps：不经常写issue，如果有哪里解释的不清楚，格式不对或者还有其他问题，非常乐意改正，谢谢）

**Comment by LSL1618** [comment]
JS代码全部凑一起看起来就很头疼，格式化一下也不难的

**Comment by LSL1618** [comment]
首先分片配置项是初始化webuploader对象的时候就已经设置好了的，结果你告诉人家有的文件不需要分片，人家傻傻分不清的。对于这种情况建议你创建2个文件上传域分别用于大文件分片上传、小文件整体上传。

**Comment by LSL1618** [comment]
```
WebUploader.Uploader.register({
	"before-send": "beforeSend"
}, {
	"beforeSend": function (block) {
		var deferred = WebUploader.Deferred();
		var file = block.file;
		var fileMd5 = file.wholeMd5; // 修改data可以控制发送哪些携带数据。
		$.ajax({
			type: "POST",
			url: obj.checkChunkPath,
			data: {
				token: uploader.options.formData.token, //文件唯一标记
				fileMd5: fileMd5, //当前分块下标
				chunk: block.chunk, //当前分块大小
				chunkSize: block.end - block.start
			},
			dataType: "json",
			success: function (data) {
				if (data.isexist == 1) { //分块存在，跳过
					deferred.reject();
				} else { //分块不存在或不完整，重新发送该分块内容
					deferred.resolve();
				}
			}
		});
		return deferred.promise();
	}
});
```

**Comment by AnAloneJaver** [comment]
```
WebUploader.Uploader.register({
	"before-send": "beforeSend"
}, {
	"beforeSend": function (block) {
		var deferred = WebUploader.Deferred();
		var file = block.file;
		var fileMd5 = file.wholeMd5; // 修改data可以控制发送哪些携带数据。
		$.ajax({
			type: "POST",
			url: obj.checkChunkPath,
			data: {
				token: uploader.options.formData.token, 
				fileMd5: fileMd5, //文件唯一标记
				chunk: block.chunk, //当前分块下标
				chunkSize: block.end - block.start//当前分块大小
			},
			dataType: "json",
			success: function (data) {
				if (data.isexist == 1) { 
					//分块存在，跳过
					deferred.reject();
				} else { 
					//分块不存在或不完整，重新发送该分块内容
					deferred.resolve();
				}
			}
		});
		return deferred.promise();
	}
});
　　感谢您的回答。
　　js没有格式化的问题，下次一定注意，不好意思。  
　　这个监听(before-upload)我没有在官网的API中找到。在API中的调用方式，是用于webuploader对象的。我尝试过使用webuploader对象来调用这监听事件，并没有效果，并且这个监听事件(before-upload)和API中的uploadBeforeSend的事件还不一致，调用方式只能写为现在这种调用方式，我知道uploadBeforeSend这个监听可以在声明webuploader对象的时候声明进去，而before-upload则不可以，可能是我对js不熟悉导致的该问题，希望before-upload这个监听事件可以写到官网的API中，调用方式
可以和uploadstart 等事件一致。
　　再次感谢您的回答，一个后端程序员尽全力想学习这个优秀的文件上传组件。
　　谢谢。

**Comment by LSL1618** [comment]
官方文档是有介绍的，只是不容易发现而已，在此[http://fex.baidu.com/webuploader/document.html#hook](http://fex.baidu.com/webuploader/document.html#hook)

**Comment by LSL1618** [comment]
顺便我也是做后端的，一样要干前端的事情。可以看看我在 [https://github.com/fex-team/webuploader/issues/3147](https://github.com/fex-team/webuploader/issues/3147) 发的参考。

**Comment by AnAloneJaver** [comment]
好的，共同进步，向大佬看齐。再次谢谢大佬。
