### ISSUE TITLE
在ie9中怎么获取上传按钮点击事件

### ISSUE THREAD

**Issue by litao1987** [fex-team/webuploader#319]
ie9上传用的flash，我想调用方法触发上传按钮事件。怎么做？

**Comment by javaxiaobai** [comment]
![timg_](https://cloud.githubusercontent.com/assets/26177072/26234665/d8de0e4a-3c98-11e7-98db-87488d4796d5.jpg)

**Comment by kk-fan** [comment]
各位 现在这个问题有解决的嘛
