### ISSUE TITLE
由于ie 大文件分块传 获取md5 慢

### ISSUE THREAD

**Issue by biewen520** [fex-team/webuploader#341]
作者弄否考虑一个折中方案
比如chunk设置开启后，表示ie firefox 都是分块了。。ie下  传大一点的文件，是及其惨的一件事。。
能否开启分块上传后，，如果不支持html5 就默认使用swf 上传。。不考虑分块。。
如果swf 不能分块读取文件这个问题没有很好的解决。。全文件读到内存 分块上传。个人觉得这个很非常恐怖。。
希望作者考虑一个折中的方案。。
这里有一个其他文件上传插件（这里不是广告啊）：
看能否有优点借鉴。。。
http://www.twinkling.cn/

**Comment by bi-kai** [comment]
@2betop IE8 flash方式上传400MB文件，内存占用1.4GB左右，切无法释放，是否有解决办法？
