### ISSUE TITLE
关于upload( file | fileId) 指定一个文件上传不生效

### ISSUE THREAD

**Issue by a-meng** [fex-team/webuploader#353]
怎么用呢，试了半天，uploader.upload()
不管是传file 对象 还是 file.id 都跟没传一样所有队列中的文件都会被执行上传操作

**Comment by ZhangChengJie** [comment]
@a-meng  我现在要用 addFiles(file)方法，可是我怎么构造一个file参数呢？ 请教一下，你是怎么传的file对象呢？
