### ISSUE TITLE
取Queue 文件队列问题

### ISSUE THREAD

**Issue by officepiano** [fex-team/webuploader#381]
看到文档中 写到

“Queue
文件队列, 用来存储各个状态中的文件。

stats
统计文件数。

numOfQueue 队列中的文件数。
numOfSuccess 上传成功的文件数
numOfCancel 被取消的文件数
numOfProgress 正在上传中的文件数
numOfUploadFailed 上传错误的文件数。
numOfInvalid 无效的文件数。
numofDeleted 被移除的文件数。
”
.......

我怎么样才能得到这些数据呢  累死 还有Base 我怎么调用

**Comment by LSL1618** [comment]
@officepiano ，怎么弄的？急需？

**Comment by AlbertKnag** [comment]
@officepiano @LSL1618 看了半天也没搞清楚如何获取到Queue对象，
文档可以考虑改进改进了！
@nwind @2betop

**Comment by zhangliyuan** [comment]
@2betop    
跟@officepiano @AlbertKnag 一样的问题：
怎么获取Queue， Queue是如何初始化的

**Comment by FlyComputer** [comment]
> 看到文档中 写到
> 
> “Queue
> 文件队列, 用来存储各个状态中的文件。
> 
> stats
> 统计文件数。
> 
> numOfQueue 队列中的文件数。
> numOfSuccess 上传成功的文件数
> numOfCancel 被取消的文件数
> numOfProgress 正在上传中的文件数
> numOfUploadFailed 上传错误的文件数。
> numOfInvalid 无效的文件数。
> numofDeleted 被移除的文件数。
> ”
> .......
> 
> 我怎么样才能得到这些数据呢 累死 还有Base 我怎么调用

uploader.getStats()
