### ISSUE TITLE
fileNumLimit可以在uploadSuccess后重新设置吗？

### ISSUE THREAD

**Issue by arieslee** [fex-team/webuploader#396]
比如：我的fileNumLimit设置的是2.
我上传成功了两张图片，然后又删除了其中一张，我想再上传一张，这个时候因为fileNumLimit的限制，应该不会再向队列中添加图片了吧

**Comment by HQS1983** [comment]
如果还有人看到这个问题，然后又不会解决，请看

[希望官方能增加一个动态修改上传 文件数量功能 ＃2927](https://github.com/fex-team/webuploader/issues/2927)

百度和很多技术博客都是复制、粘贴，根本没用，那些懂的大神，又没详细解释

多扯一句 uploader.refresh(); //重新实例化 这个对你可能有用
