### ISSUE TITLE
调用addFiles的file参数如何设置？

### ISSUE THREAD

**Issue by ejzhang** [fex-team/webuploader#411]
uploader.addFiles({id:'WU_FILE_0',name:'test.txt',status:'queued'});无效啊，谢谢！

**Comment by swaron** [comment]
<input  id="file" type="file" onchange="...">

files = document.getElementById('file').files

var webuploader = new WebUploader.Uploader(...);
...
//for file in files
var wuFile = new WebUploader.File(new WebUploader.Lib.File(WebUploader.guid('rt_'),file));
webuploader.addFile(wuFile);
