### ISSUE TITLE
android手机上传jpg图片，开启压缩后上传失败

### ISSUE THREAD

**Issue by zsjdream** [fex-team/webuploader#444]
在android上测试，开启压缩后，直接alert FILE的数组发现name很奇怪，类似于Blobxxxxxx这样的，size也不对，为0，导致后端上传出现问题，在ios上测试就是正常的。
http://game.zhengguzhiba.com/wxapi.php/uploader/web_uploader
这个地址可以测试，选择图片后会直接弹出 FILE数组的信息。

**Comment by usenrong** [comment]
请问问题解决了吗 我们用手机浏览器上传 文件大小全是0 求教
