### ISSUE TITLE
希望得到工作人员回复，这样子行的通不..

### ISSUE THREAD

**Issue by sailstar** [fex-team/webuploader#445]
<p>一个月了，还是觉得DEMO给出的调用方案不太合适，如果一个页面里要出现很多个上传框，这种调用方法会疯掉的。<br />
因为是想能灵活地应用这个上传插件，同时也希望webuploader能做的更好些，所我的一些想法放出来，看看能不能实现。</p>

<p>HTML代码：</p>

<p><br />
  &lt;div id=&quot;imageUploder1&quot;&gt;<br />
  &lt;div class=&quot;uploader-list&quot;&gt;<br />
  &lt;div class=&quot;uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;/div&gt;<br />
  <br />
  &lt;div id=&quot;imageUploder2&quot;&gt;<br />
  &lt;div class=&quot;uploader-list&quot;&gt;<br />
  &lt;div class=&quot;uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;button class=&quot;btn btn-default uploader-submit&quot;&gt;开始上传&lt;/button&gt;<br />
  &lt;/div&gt;<br />
  <br />
  &lt;div id=&quot;imageUploder3&quot;&gt;<br />
  &lt;div class=&quot;newlist uploader-list&quot;&gt;<br />
  &lt;div class=&quot;newpicker uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;button class=&quot;btn btn-default uploader-submit&quot;&gt;开始上传&lt;/button&gt;<br />
  &lt;/div&gt;<br />
  ....<br />
  &lt;div id=&quot;fileUploder1&quot;&gt;<br />
  &lt;div class=&quot;uploader-list&quot;&gt;<br />
  &lt;div class=&quot;uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;/div&gt;<br />
  <br />
  &lt;div id=&quot;fileUploder2&quot;&gt;<br />
  &lt;div class=&quot;uploader-list&quot;&gt;<br />
  &lt;div class=&quot;uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;button class=&quot;btn btn-default uploader-submit&quot;&gt;开始上传&lt;/button&gt;<br />
  &lt;/div&gt;<br />
  <br />
  &lt;div id=&quot;fileUploder3&quot;&gt;<br />
  &lt;div class=&quot;newlist uploader-list&quot;&gt;<br />
  &lt;div class=&quot;newpicker uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;button class=&quot;btn btn-default uploader-submit&quot;&gt;开始上传&lt;/button&gt;<br />
  &lt;/div&gt;<br />
  ...</p>

<p><br />
  这里不为每个上传框里的元素设置ID，是为了方便在调用时可以在同一页面使用多个webuploader实例。正如上次<strong><a href="https://github.com/2betop">2betop</a></strong>所说，UI不管怎么写总有人觉得不爽。但同一系统的上传UI风格肯定是统一的。如果有变化，上面通过在class属性里增加如newlist/newpicker，或uploader里的元素实现不同风格。</p>

<p>在JS中，使用$(&quot;#imageUploder1 .uploader-list)、$(&quot;#imageUploder2 .uploader-list)...或$(&quot;#imageUploder1&quot;)find(&quot;div[class$='uploader-list'&quot;])、$(&quot;#imageUploder2&quot;)find(&quot;div[class$='uploader-list'&quot;])...来得到不同上框的对象。以实现显示不同的内容。同样，$(&quot;#imageUploder1 .uploader-picker)、$(&quot;#imageUploder2 .uploader-picker)...或$(&quot;#imageUploder1&quot;)find(&quot;div[class$='uploader-picker'&quot;])、$(&quot;#imageUploder2&quot;)find(&quot;div[class$='uploader-picker'&quot;])...<br />
  可以得到不同的文件选择按钮。上传按钮也是如此。这样，只需要传递不同的uploader的ID到定义好的各种响应方法中，如function fileQueued(uploaderId){..}、function fileQueued(uploaderId){..}就可实现对应的功用。另外，我觉得给出的例子的这种JS内部函数的写法不适合做插件，也不好重复使用。</p>

<p>在初始化配置方面，各个上传框的配置可能是不一样的，我觉得有一个叫ztree的初始化插件值得参考。给出一个配置文件config.js自定义不同的setting，如:<br />
  imageSetting{auto:true,...}、imagelistSetting{auto:false,...}等。在需要初始化时，把对应的配置传递出去。</p>

<p>var imageUploader1 = WebUploader.create(&quot;imageUploder1&quot;, imageSetting);<br />
  var imageUploader2 = WebUploader.create(&quot;imageUploder2&quot;, imagelistSetting);<br />
  ...或<br />
  var imageUploader1 = WebUploader.create($(&quot;#imageUploder1&quot;), imageSetting);<br />
  var imageUploader2 = WebUploader.create($(&quot;#imageUploder2&quot;), imagelistSetting);<br />
  ..</p>

<p>这样，如果插件已经写的好了，到时一个页面只要一个实例，最终的调用方法会是这样：<br />
  &lt;div id=&quot;imageUploder&quot;&gt;<br />
  &lt;div class=&quot;uploader-list&quot;&gt;<br />
  &lt;div class=&quot;uploader-picker&quot;&gt;选择文件&lt;/div&gt;<br />
  &lt;/div&gt;<br />
  &lt;script&gt;<br />
  $(document).ready(function(){<br />
  var imageUploader = WebUploader.create(&quot;imageUploder&quot;, imageSetting);<br />
  });<br />
  &lt;/script&gt;</p>

<p>其中imageSetting已经在config.js做好对应的配置。</p>

**Comment by yuechen323** [comment]
不错

**Comment by 1113126226** [comment]
@2betop 非常感谢你，我看了好久终于找到个思路了，虽然还没解决。
提问者的态度真不好
