### ISSUE TITLE
=========请教大神怎么跳过一个分片？服务端都写好了就差这个操作了，急，在线等啊==========

### ISSUE THREAD

**Issue by i7moblade** [fex-team/webuploader#502]
以下是我的JS代码 $has_checks是从服务端返回来的已存在的分片标识，请问怎么在这里跳过已存在的分片请求？
uploader.on("uploadBeforeSend", function(block, data, headers){
        var index = $.inArray(data.chunk.toString(), $has_checks);
        if(index >= 0){
            console.log('跳过分片');
        }else{
            //继续上传
        }
    })

**Comment by shangyue1110** [comment]
注册before-send的方法必须要在WebUploader实例化之前才能生效~
