### ISSUE TITLE
【选择图片】被隐藏重新显示后倒置无法进行选择图片

### ISSUE THREAD

**Issue by cipchk** [fex-team/webuploader#514]
# 重现
1. 上传图片面板加载时就 `display="none"`，当需要上传时，点击并显示上传图片面板，然后再点选择图片。
2. 实例化 WebUploader 放在 html部分 后面。

这个时候不管怎么点击【选择图片】按钮都无效。

原因是调用`refresh()`时，会重绘【选择图片】按钮的最上层的透明块，但此时整个面板被隐藏，倒置 `button.outerWidth()` 获取的宽度直接为`0`，故而 `click` 时无法触发事件。

```
            refresh: function() {
                var shimContainer = this.getRuntime().getContainer(),
                    button = this.options.button,
                    width = button.outerWidth ?
                            button.outerWidth() : button.width(),

                    height = button.outerHeight ?
                            button.outerHeight() : button.height(),

                    pos = button.offset();

                width && height && shimContainer.css({
                    bottom: 'auto',
                    right: 'auto',
                    width: width + 'px',
                    height: height + 'px'
                }).offset( pos );
            },
```
# 解决

我是重新注册  `ready` 事件，并隐藏上传面板。

```
on('ready', function () {
            upArea.hide();
        })
```

在官网文档里面并无这个事件说明，我也没有完整的看源代码确保 `ready` 事情是可以重新注册了，但使用下来没有发现问题。

我不确认这算不算一个 bug，希望此 issues，可以帮到各位。

其实很希望增加一个控件加载完成后有个事件触发，这样可以做些事情。

以上。

**Comment by seasonhuang** [comment]
为什么每次refresh都要设置offset？

**Comment by airclear** [comment]
$(window).resize()
这个方法也可以

**Comment by asea1718** [comment]
@airclear 有没有具体点的$(window).resize()实现方式呢？我这用了，但是第一次点击没反应，要第二次开始才可以上传！

**Comment by standbym** [comment]
或者直接设置下宽高
.on('ready', function () {
    var $div = $('.webuploader-element-invisible').parent();
    $div.css({'width':'80px','height':'40px'});
})

**Comment by wzapk** [comment]
我也遇到这个问题，按照 @cipchk 思路，在页面的jquery ready中加入jQuery('#uploader').hide()解决

**Comment by javaxiaobai** [comment]
我的这个问题还没解决呢

**Comment by sycct** [comment]
@airclear 你给出的这个方案，解决了我的问题。谢谢
