### ISSUE TITLE
ie8js冲突问题。去掉var uploader = WebUploader.create({});ie8就不报错了，所以问题定位到是不是这个插件跟jquery.min.js有冲突？

### ISSUE THREAD

**Issue by yanliqing** [fex-team/webuploader#631]
网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
时间戳: Tue, 2 Dec 2014 08:20:51 UTC

消息: Runtime Error
行: 977
字符: 17
代码: 0
URI: http://192.168.1.85:8080/estudy/center/networkdisk/networkdisk.action

消息: 由于出现错误 80020101 而导致此项操作无法完成。
行: 2
字符: 11482
代码: 0
URI: http://192.168.1.85:8080/estudy/static/js/jquery.min.js

**Comment by 317365887** [comment]
你解决了这个问题了吗?

**Comment by suifengfengye** [comment]
我也遇到了这个问题，解决了么？
