### ISSUE TITLE
上传文件怎么出现中文乱码，

### ISSUE THREAD

**Issue by TEMK6** [fex-team/webuploader#656]
还有就是文件 怎么会自动添加下面这部分内容
-----------------------------11142258241763
Content-Disposition: form-data; name="id"

WU_FILE_0
-----------------------------11142258241763
Content-Disposition: form-data; name="name"

test123.txt
-----------------------------11142258241763
Content-Disposition: form-data; name="type"

text/plain
-----------------------------11142258241763
Content-Disposition: form-data; name="lastModifiedDate"

Wed Dec 10 2014 11:37:19 GMT+0800
-----------------------------11142258241763
Content-Disposition: form-data; name="size"

34
-----------------------------11142258241763
Content-Disposition: form-data; name="file"; filename="test123.txt"
Content-Type: text/plain

**Comment by leeyoungae** [comment]
我也是遇到，我怎么设置页面编码好像都没有效果    @我目前的解决方法是用
iconv("UTF-8","gb2312",$file_path);
就不会出现乱码。
