### ISSUE TITLE
透明png，缩略图透明块变成黑色

### ISSUE THREAD

**Issue by monkeycraps** [fex-team/webuploader#693]
按照官方例子做的
jquery file upload 这块用的 canvas 实现，可以支持透明预览

**Comment by Tianxinglang** [comment]
![image](https://cloud.githubusercontent.com/assets/19465245/18075315/361e4f1e-6ea6-11e6-830f-378320befbe0.png)
是这么配置吗，为什么我这边的反白图还是黑色的背景
