### ISSUE TITLE
(gh-pages评论)Getting Started

### ISSUE THREAD

**Issue by 2betop** [fex-team/webuploader#71]
以下评论将自动发布在[Web Uploader 快速开始教程](http://fex.baidu.com/webuploader/getting-started.html)页面里面。

**Comment by wgfsimple** [comment]
上传文件时，怎么在打开文件的时候限制文件类型呢（文件类型不要所有文件），比如只能上传word、excel、zip、rar

**Comment by zuanke** [comment]
官网就没有一个完整的文件上传demo可供下载吗，急死了！！！

**Comment by ffzhihua** [comment]
官网就没有一个完整的文件上传demo可供下载吗，急死了！！！

**Comment by ffzhihua** [comment]
我在手机上测试，上传以后都视频的字节数都为0，不知道什么原因。html5支持，急

**Comment by huawq** [comment]
webUploader能在linux服务器下使用吗

**Comment by onilylove** [comment]
太悲剧了。 我用你们的上传组件，和妹子UI一起放在选项卡中。 居然发生css冲突了。

**Comment by yizenghui** [comment]
引用"ffzhihua commented on 12 Feb 我在手机上测试，上传以后都视频的字节数都为0，不知道什么原因。html5支持，急"
同样，在手机上把拍到的.jpg相片上传到服务器后，无法正常获得数据；手机上.png的上传正常。使用电脑上传正确。
期待回复和处理。

**Comment by hellocpu** [comment]
TO 2betop大哥，你好，我的情况是这样的：在IE10里，上传文件是没问题的，但是在IE9下上传不了，通过抓包，发现IE9下，消息 头儿的accept:text/*，而IE10 是accpet:*， 是不是这个原因导致我IE9上传不了，另外在IE9下JPG格式的可以上传成功，但其它格式不可以。
期待您的回答。

**Comment by hellocpu** [comment]
TO 2betop大哥，你好，我的情况是这样的：在IE10里，上传文件是没问题的，但是在IE9下上传不了，通过抓包，发现IE9下，消息 头儿的accept:text/*，而IE10 是accpet:*， 是不是这个原因导致我IE9上传不了，另外在IE9下JPG格式的可以上传成功，但其它格式不可以。
期待您的回答。

**Comment by Astlvk** [comment]
你好，webuploader支持对button标签的绑定吗？ie下我绑定button标签，点击后没有效果。chrome绑定button标签，就没问题。

**Comment by Astlvk** [comment]
@2betop 你好，webuploader支持对button标签的绑定吗？chrome绑定button标签，没问题。
ie下我绑定button标签，点击后没有效果。ie10 11，点击无法弹出选择框。
ie10以下，快速的双击倒是能弹出，但是一下一下的点击还是无法弹出。Firefox下也是不能弹出。
只能用div来做按钮了么？

**Comment by RealFeeling** [comment]
这个用JSP的话怎么获取数据呢，在上传server 这个URL里写servlet的路径吗？servlet该怎么获取和返回上传成功呢？

**Comment by fanmengqi** [comment]
初始化之后，每上传一张图片，上传按钮会移动位置，但object元素 还在原位置，有什么方法能重新加载object元素的位置吗？

**Comment by jishujian** [comment]
请问一张表单里边有2个图片上传的地方应该怎么做？

**Comment by dingziding990** [comment]
@codejm，已上传的图片，编辑时候初始化这些图片的时候，是怎么传给插件的呢？js如何写的呢，求教

**Comment by youbl** [comment]
fex.baidu.com里有个resize参数，实际api里没有，赶紧改了吧，坑我啊，查了半天，才发现是        compress: false

**Comment by yzwk** [comment]
@2betop 我的站里有多个上传图片的地方，但要保存到不同路径下的文件夹，我需要在哪设置或者我可以怎么样实现，JS的参数中我没有看到相应的参数。盼复，万分感谢

**Comment by prettythings** [comment]
这个只能上传图片文件吗？ 不可以压缩包或者视频文件吗？

**Comment by 905996491** [comment]
在微信内置浏览器中上传图片，请问如何在对话框中初始出相机选项，请问有什么属性可以控制么？

**Comment by 905996491** [comment]
求大神解惑。。。

**Comment by zhangchao123** [comment]
IE里上传，在这句总是报错
if ( !type ) {
                throw new Error('Runtime Error');
            }
麻烦能帮下忙吗

**Comment by zhangchao123** [comment]
就在这个里面， 貌似不能判断是html还是flash
Runtime.create = function( opts, orders ) {
            var type, runtime;
    
            orders = orders || Runtime.orders;
            $.each( orders.split( /\s*,\s*/g ), function() {
                if ( factories[ this ] ) {
                    type = this;
                    return false;
                }
            });
    
            type = type || getFirstKey( factories );
    
            if ( !type ) {
                throw new Error('Runtime Error');
            }
    
            runtime = new factories[ type ]( opts );
            return runtime;
        };

**Comment by blacider** [comment]
我用了您们写的demo,功能是可行的
但是刚打开页面时选择图片按钮是不能点击的,此时要打开开发者工具(或者关闭开发者工具),瞬间按钮就可以点击了.请问这是什么问题 又该如何解决

我的环境{
ox x 10.4 chrome最新版 
}
急,在线等 : )
谢谢

**Comment by tmaccx** [comment]
为什么要销毁view？
初学前端，很多地方不懂，多多包涵。

**Comment by dscideal** [comment]
请问上传成功后，后台的返回值，应该怎么取。。uploadSuccess',function( file, response )，，file和response 各包含什么值。。。求解。。取不到返回的值，，这两个是object对象

**Comment by hwbox** [comment]
firefox9 不安装flash插件不能使用本控件啊。能否明确使用html5only的firefox的最低版本?

**Comment by liu-lgy** [comment]
你好 请问一下可以自定义文件上传的目录么

**Comment by SiriusGuo** [comment]
可以自定义文件上传目录，但是我觉得这不是插件的职能范围。
后台在接受到文件流之后，存到哪里应该是后台应该做的事情。

**Comment by along7599** [comment]
server中的服务只能是PHP的或者JAVA servlet的吗，可不可以用asp.net写，有没有示例？

**Comment by Hollson** [comment]
能不能搞一个选择某张图设为封面的效果

**Comment by CsliYang** [comment]
大神，Web Uploader不支持jquery1.9.1吗？我们项目使用的是jquery1.9.1，但是上传图片按钮出不来，把jquery换成1.8.3就可以显示，这个问题困扰我三天啦！如果有这种兼容性的话还是卸载quick start里，不然很多新手喜欢使用最新版的，会导致出不来！

**Comment by MrLiJM** [comment]
WebUploader的API说的不是很清楚
例如：(1)限制单个文件长传的的大小属性的fileSingleSizeLimit的单位是什么，是KB、M还是其他
          (2)获取文件的状态没说明，使用file.Status()

**Comment by tianjun5200** [comment]
点击文件上传之后  php端显示文件非法上传怎么处理

**Comment by HJonping** [comment]
怎么初始化数据呀  我按照教程做了 但是没反应呀 弄了好久都不行

**Comment by MrLiJM** [comment]
教程写的不是很完善，我用的是JSP+Servlet写的简单的例子，如果需要，发你邮箱@HJonping

**Comment by HJonping** [comment]
好呀 非常感谢 我的邮箱是695069256@qq.com

**Comment by MrLiJM** [comment]
已发送

**Comment by HJonping** [comment]
非常感谢，我已经收到了

**Comment by HJonping** [comment]
上传文件夹里边的文件名出现了乱码 怎么解决呢 有谁遇到这个问题过吗？

**Comment by MrLiJM** [comment]
转码就行了，好像是ISO-8859-1转UTF-8就行了

**Comment by HJonping** [comment]
我的代码文件都是utf-8格式的了 但是如果上传的文件是英文名字的话 就不会出现乱码

**Comment by MrLiJM** [comment]
是用二进制流传过去的吗？你先转码试一下

**Comment by HJonping** [comment]
你是说转上传的文件 还是代码文件呀

**Comment by MrLiJM** [comment]
上传文件时，使用二进制流，后台转码ISO-8859-1转UTF-8

**Comment by HJonping** [comment]
接收端的文件是用官网的 upload.php  但是怎么转呢 我用我的方法不对呀

**Comment by MrLiJM** [comment]
额，PHP不清楚，我用的是JSP+Servlet做的

**Comment by HJonping** [comment]
嗯 已经解决了 谢谢

**Comment by HJonping** [comment]
可以实现异步上传吗？

**Comment by MrLiJM** [comment]
这个本来就是异步的吧

**Comment by HJonping** [comment]
异步刷新 但是上传后不是我想要的效果 像ajaxUpload插件使用效果一样  百度云盘上传文件后页面局部刷新

**Comment by MrLiJM** [comment]
这个好控制，你将要刷新的部分放在iframe里面不就行了吗？

**Comment by HJonping** [comment]
那是要自己再判断罗  还是webupload支持这个功能

**Comment by MrLiJM** [comment]
肯定是自己啊，当文件上传完成之后，刷新相应的iframe

**Comment by HJonping** [comment]
嗯嗯 谢谢

**Comment by HJonping** [comment]
问下怎么获取接收端返回的文件信息呢

**Comment by chengky** [comment]
当页面由多个标签页组成（通过隐藏、显示）控制，如果初始隐藏的页面中有上传控件，触发选择文件的按钮可点击区域变的很小

这是正常的非隐藏区域的按钮：
<div id="rt_rt_19vf7rjquko5n3r1f0uq6212ca1" style="position: absolute; top: 0px; left: 0px; width: 94px; height: 38px; overflow: hidden; bottom: auto; right: auto;"><input type="file" name="file" class="webuploader-element-invisible" multiple="multiple"><label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label></div>

这是正常的隐藏区域的按钮：
<div id="rt_rt_19vf7rjqviptgqsbhr4f211uj3" style="position: absolute; top: 0px; left: 0px; width: 30px; height: 20px; overflow: hidden; bottom: auto; right: auto;"><input type="file" name="file" class="webuploader-element-invisible" multiple="multiple"><label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label></div>

直接用的官方的DEMO，没调用任何外部样式。如果使用一些bootstrap样式，隐藏区域的按钮可点击区域还可能是width:1px;height:1px

**Comment by MrLiJM** [comment]
你要意思是要显示按钮还是隐藏按钮，或者是手动触发还是自动触发按钮？

**Comment by chengky** [comment]
@MrLiJM 是标签页的形式，页面部分是显示，部分是隐藏的，如果上传控件在隐藏的部分中，按钮的大小获取不正常

**Comment by fhyfhy17** [comment]
我的问题是：上传后的文件，后期需要修改，查询时我只有图片的网络地址，这个时候想要新建File,应该怎么做?
怎么主动触发添加文件事件呢?怎么新建文件呢？

**Comment by Narcissist1** [comment]
Uncaught ReferenceError: $list is not defined 我在console里面得到这个错误，有人知道为什么吗？？

**Comment by Skycheng168** [comment]
@BaiduFE ,问一下怎么在压缩图片(compress)之前获取图片尺寸。我想判断图片尺寸大小，比如：低于100*100px的不允许上传。

**Comment by ericandli** [comment]
按照教程写的，使用纯html,但是在初始化后，选择文件按钮无法渲染，还是和普通文本一样，这是什么原因？

**Comment by angustw** [comment]
按照教程写的,服务端获取不到数据,检查发现xhr发送的FormData是个空对象怎么回事.

**Comment by tianjun5200** [comment]
formdata 要传一个表单对象

**Comment by angustw** [comment]
后端用express获取上传的文件,req.body无数据,难道post的文件不是放在req.body里?

**Comment by angustw** [comment]
其他人没有遇到这个问题吗?厂长&fex帮帮忙啦!

**Comment by a630574510** [comment]
请问如何实现.net断点续传功能，急救！！！

**Comment by tyut8518** [comment]
hi 你好 我想问下怎么获得队列对象，
貌似校验失败的文件也会加入队列，怎么删除校验不通过的文件？

**Comment by zy1026** [comment]
@codejm @2betop 问下我上传成功了，我想要修改的时候怎么把图片展示在控件里面

**Comment by z378275769** [comment]
@2betop 您好，我想问下这个插件怎么动态添加参数？formdata只是初始化的时候赋值，现在我传给服务器端的参数要动态添加，这个怎么添加？谢谢了

**Comment by xuyudong** [comment]
很多人不知道怎么在后台接受数据，我本身是用php的，提供个方法
![1](https://cloud.githubusercontent.com/assets/12404091/11604945/c4df965a-9b2e-11e5-8bbb-cd17cd79daac.jpg)

然后利用我们强大的chrome调试器，看看后台接受到了什么数据？
![2](https://cloud.githubusercontent.com/assets/12404091/11604955/f425da00-9b2e-11e5-96ba-b10d9412b8d2.jpg)

可以看到是二维数组，你就懂图一为什么这么写了吧？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by zhuanghuiliang** [comment]
请问有没有属性设置禁止哪些类型的文件上传？

**Comment by isoks** [comment]
我想在修改页面内使用webuploader，进入的时候先把后台返回的图片文件加到webuploader里该如和操作

**Comment by tsjw5104256** [comment]
@2betop 你好，我们后台返回的是一个图片的路径，不是json格式，在ie8.9的时候会出错me._responseJson = me._response ? p(me._response) : {};，有什么解决的办法嘛？

**Comment by strong-ge** [comment]
@2betop 你好，我在使用webuploader和BootstrapValidator时冲突怎么办？

**Comment by zarcck** [comment]
看到好多说IE789不行的，我之前也被坑了，总结了一下 1、网络里查看下swf文件是不是404了 2、不要对上传组件内部元素做show() or hide()操作，不然会报错

**Comment by TclComupter** [comment]
将uploader定义成全局变量，为什么方法全都失效了？

**Comment by Destin-LYH** [comment]
我用教程里的代码实验，结果发现按钮点不了，检查代码是这样的：
![1](https://cloud.githubusercontent.com/assets/17928872/13879609/4aed1a30-ed53-11e5-9896-32d33f9a5ff2.jpg)
是在bootstrap的模态框里创建的

**Comment by zengAlex** [comment]
[图片已经上传成功了，如何在点击“换一张”按钮的时候，传个参数上去尼？这个是自动上传的
![eolck kb l3 xexx h1ryv](https://cloud.githubusercontent.com/assets/13888110/13947559/3d55b3b8-f056-11e5-869c-ce6fbc1bebbb.png)

**Comment by zengAlex** [comment]
我的页面有多个类名相同的按钮，因为我页面有很多个不同类型的文件上传，且对应到不同的id,我想要点击后才实例化他，要怎么做尼？

**Comment by visvoy** [comment]
我凑！太扯淡了，最重要的如何触发上传的方法没写在页面里，api特么也没有，得看get-started.js才知道，什么啊

**Comment by MySecret** [comment]
严格模式下报错啊大哥。。。怎么解决

**Comment by viyiu** [comment]
我这里用的是symfony框架，然后直接初始化之后，点击选择照片按钮，但是没有反应，然后按一下firebug，就能选择照片了，在chrome浏览器下，是按一下f12就可以选择照片。但是我直接运行demo之后，点击是有反应的。

**Comment by chenlong11** [comment]
我用upload初始化一个隐藏的选择按钮
在使用的时候才将按钮显示出来 
然后发现点击按钮没有反应

**Comment by chenlong11** [comment]
我用upload初始化一个隐藏的选择按钮
在使用的时候才将按钮显示出来 
然后发现点击按钮没有反应
请问下这种情况有什么解决办法么？

**Comment by lw83942** [comment]
![qq 20160611113405](https://cloud.githubusercontent.com/assets/14037079/15982900/84042e1e-2fc8-11e6-8e7a-623e2414616c.png)
我把demo代码放到bootstrap栅格中结果生成的div宽高只有1px，鼠标点不到，浏览器窗口改变时就恢复82*64宽高，请问这是什么原因呢？我试了改成强制flash是没有这个问题的，不过后台已经成功了返回json数据，页面却总是跳错误方法，打印迟来错误代码就是http，请问这个怎么解决

**Comment by EricInSH** [comment]
是否支持多种文件格式一起上传呢？
accept: {
title: 'logfile',
extensions: 'tar,txt,zip',
mimeTypes: 'text/plain,application/zip'
},

这样设置可以吗？

**Comment by DeronMeng** [comment]
怎么不支持TIIF图片呢？

**Comment by find123** [comment]
你好，请问在IE6和IE7下实现图片预览，我要在哪个函数或者哪个事件下操作呢？谢谢！

**Comment by find123** [comment]
监听不到uploadSuccess事件是为什么呢

**Comment by ytlviv** [comment]
编辑功能能给个接口么，服务端给你一个图片列表 插件就能显示出来 编辑删除，这样多好

**Comment by xiaojl** [comment]
在做上传文件的时候，我把按照步骤把代码拷贝进去，但是点击开始上传按钮的时候，没有反映也没有出现进度条，期待您的指导，下面是我的代码：
$(function(){

var uploader = WebUploader.create({

    // swf文件路径
    swf: 'Uploader.swf',

    // 文件接收服务端。
    server: 'http://webuploader.duapp.com/server/fileupload.php',

    // 选择文件的按钮。可选。
    // 内部根据当前运行是创建，可能是input元素，也可能是flash.
    pick: '#picker',

    // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
    resize: false
});
//由于webuploader不处理UI逻辑，所以需要去监听fileQueued事件来实�

var $list = $('#thelist')
uploader.on( 'fileQueued', function( file ) {
    $list.append( '<div id="' + file.id + '" class="item">' +
        '<h4 class="info">' + file.name + '</h4>' +
        '<p class="state">等待上传...</p>' +
    '</div>' );
});

// 文件上传过程中创建进度条实时显示。
uploader.on( 'uploadProgress', function( file, percentage ) {
    var $li = $( '#'+file.id ),
        $percent = $li.find('.progress .progress-bar');

    // 避免重复创建
    if ( !$percent.length ) {
        $percent = $('<div class="progress progress-striped active">' +
          '<div class="progress-bar" role="progressbar" style="width: 0%">' +
          '</div>' +
        '</div>').appendTo( $li ).find('.progress-bar');
    }

    $li.find('p.state').text('上传中');

    $percent.css( 'width', percentage * 100 + '%' );
});

//文件成功失败的处理
uploader.on( 'uploadSuccess', function( file ) {
    $( '#'+file.id ).find('p.state').text('已上传');
});

uploader.on( 'uploadError', function( file ) {
    $( '#'+file.id ).find('p.state').text('上传出错');
});

uploader.on( 'uploadComplete', function( file ) {
    $( '#'+file.id ).find('.progress').fadeOut();
});


});

**Comment by starsun2013** [comment]
你好，我宽度和高度都设置了1600，但是当上传完之后，发现图片还是1600*1600，不过在四周加上一圈黑色的底色，这是怎么回事？谢谢

**Comment by phpcolt** [comment]
感觉看明白了，在理解一下。一会儿尝试来写

**Comment by AkaShiro** [comment]
您好！我想问，文件接收服务端是做什么的？

**Comment by landlordxu** [comment]
webuploader在bootstrap模态框中使用时候无法点击

**Comment by Thinkpad93** [comment]
$list.append( '<div id="' + file.id + '" class="item">' +
        '<h4 class="info">' + file.name + '</h4>' +
        '<p class="state">等待上传...</p>' +
    '</div>' );

请问一下这里的  $list  是从那里来的呢？

**Comment by qq504884370** [comment]
为啥我复制上以后，除了HTML有“选择图片”4个字以外，点击什么都没有反应？

**Comment by Lucxl** [comment]
非常赞，只是在谷歌52版本上有瑕疵，什么时候修复

**Comment by Thinkpad93** [comment]
想请问一下，后台接收的PHP文件是怎么处理的，官网的那个PHP接收地址演示不行啊？

**Comment by yingyuedi** [comment]
我想在选择文件后，上传之前读取excel表的内容，请问如何在上传前，在客户端获取到这个文件？或者文件的本地路径？谢谢

**Comment by fengxingaotian** [comment]
按照上面demo写的代码，怎么点击选择按钮就是没任何反应，js也没报错

**Comment by yingyuedi** [comment]
@fengxingaotian 你的flash路径不对

**Comment by xuJianH** [comment]
按照demo写的，但是在ie9及以下弹不出文件选择框，怎么回事

**Comment by VeigarH5** [comment]
点击上传怎么没反应，不是有个绑定点击打开附件选择的pick吗，上传按钮不需要绑定事件吗

**Comment by mandy201610** [comment]
@2betop me._responseJson  = me._response ? p(me._response) : {} 这个再ie下上传文件时会报错 上传图片正常 另外 下载的压缩包里的文件都会用到吗  实际引入的只有三个额

**Comment by gtgtkiss** [comment]
@2betop 
![image](https://cloud.githubusercontent.com/assets/23068758/19712763/2459a41e-9b73-11e6-9ef7-e585831baf51.png)

grunt 
![image](https://cloud.githubusercontent.com/assets/23068758/19712783/47acda1c-9b73-11e6-8390-205b617ac18b.png)
使用zepto的情况，打包完这个还是会报错

**Comment by bDreams** [comment]
uploadProgress 上传进度事件无效，在上传完成后突然进入这个事件，进度随之变为百分百，这是什么问题？

**Comment by referr** [comment]
不支持 ie 浏览器传一张以上数量照片的吗？起他浏览器都可以，ie传第二张就报错。。。。

**Comment by kenuocn** [comment]
怎么让页面一加载就显示fine上传文件模式

**Comment by jozhi** [comment]
按照上传文件的 demo 来，结果是点击上传按钮无效；
按照上传图片的 demo 来，结果是从点击上传图片按钮到弹出系统文件预览选择文件框的时间超长；
环境是 OSX 10.10.5  ，chrome 最新版

**Comment by 18410717913** [comment]
怎样将已经上传玩的图片在读取信息的时候加入webuploader的队列

**Comment by wangzongxu** [comment]
BUG：假设后缀有写限制，当文件名没有后缀的话，会略过后缀校验。

**Comment by loveyuxiang** [comment]
我是新手，为什么用官方的demo里面的图片上传，我复制代码到本地，然后该引入的文件都引入了，检查了好几遍，可是打开页面后，页面上就是4个字 选择图片 而不是一个按钮，然后点也点不了。捅咕两天了没整明白，求教。

**Comment by loveyuxiang** [comment]
其实版主你可以试一下，复制网站上的demo ，肯定不好使。

**Comment by HMBlack** [comment]
第一种demo怎么设置选择文件后自动上传啊，设置那个auoto:true后应该还要别的修改吧

**Comment by yjjdick** [comment]
谷歌浏览器看实例缩略图能出来，自己做的demo其他功能都正常uploader.makeThumb回调进不来是怎么回事

**Comment by sanxing91221** [comment]
原来的插件功能限制，被推荐来看你你的这个，因为很急，结果看了很懵逼！
完全可以配置参数，进度条是否显示进度，是否预览图片，是否显示是否多传等等，但是在这里没有看到明确的列出，说实话我看的时间我都可以自己做出来一个了，图方便了结果实现完整功能后发现比我的html行数还多！！！

**Comment by lz9ken** [comment]
为什么  点击选择文件 只有点击左上角才会有效果，F12后就恢复正常了额？？？？？？？

**Comment by huojianan** [comment]
为什么压缩图的src是base64的，不想要base64的代码可以吗？

**Comment by Imskying** [comment]
您好，我想咨询一下这个chunkSize的具体大小设置，您有推荐意见么？感谢~~

**Comment by bluejayson** [comment]
初学者，几乎看不懂，但是很有兴趣

**Comment by CheckyChen** [comment]
一个页面有两个选项卡，默认第一个选项卡激活，当把上传控件放在第二个选项卡的时候，点击上传按钮没反应，什么原因呢？

**Comment by zsb197590** [comment]
我想问一下，每次一选择图片，手机浏览器就会重启，我实在找不到原因，请大神指教。

**Comment by Patricik** [comment]
为什么我下载的东西运行不出来

**Comment by wusuzhou** [comment]
你好，请问调用下面的代码，但是回调函数中的第二个值src返回的值只有“data ，”。并没有返回来完整的url值
// 创建缩略图
    // 如果为非图片文件，可以不用调用此方法。
    // thumbnailWidth x thumbnailHeight 为 100 x 100
    uploader.makeThumb( file, function( error, src ) {
        if ( error ) {
            $img.replaceWith('<span>不能预览</span>');
            return;
        }

        $img.attr( 'src', src );
    }, thumbnailWidth, thumbnailHeight );

**Comment by NiceJason** [comment]
文件上传失败后 怎么获取后端传来的信息（Json串） 单一个reason不知道怎么用

**Comment by NiceJason** [comment]
这个是BUG吗 选取文件后 如果文件里面没有任何内容 则无法选取（即选取，确定后没任何效果）

**Comment by llc1994** [comment]
BASE_URL is not defined 这个怎么解决 求大神回去

**Comment by llc1994** [comment]
BASE_URL is not defined 这个怎么解决 求大神回复

**Comment by q57528** [comment]
文件版那个，如果选中了文件怎么撤销

**Comment by lzyacg** [comment]
![image](https://user-images.githubusercontent.com/31235805/30009516-a7a30246-915b-11e7-816a-887d4061b239.png)这种类型的支持吗？

**Comment by samlin88** [comment]
在IE8下无法使用webuploader，提示的错误是“Rutime Error”，测试时要在只有最高版本为IE8时才会这样

**Comment by jyjlzw** [comment]
可以一次性选择多个文件吗？

**Comment by scot123123** [comment]
请教一下，为什么同一个文件上传了三次，设置threads 也不起作用

**Comment by githubxlb** [comment]
能否实现一起请求发送多张图片

**Comment by jiyuwangqi** [comment]
小白请教,代码中"$img"或者"$list";
'$'后面直接跟字母,这种写法是来自哪里,不太明白

**Comment by lixindada** [comment]
为什么我点开始上传没有反应呢

**Comment by mengzhaolis** [comment]
引入了教程中的**css/jq/还有一个版本2.1.4的jquery**但是在使用的过程中报错**$list is not defined**这是什么原因啊

**Comment by lxqever** [comment]
只能上传图片么，可以上传所有文件格式，怎么配置

**Comment by weilian-peng** [comment]
我想上传文件成功后，，可以直接在页面中浏览他的文本内容，并且可以对其文本进行修改，然后保存；
这个功能还要用到什莫呢？？如何才可以编辑上传文件的内容呢？

**Comment by xtgjfge** [comment]
haha

**Comment by weilian-peng** [comment]
do  you  know how to solve that question??




发自网易邮箱大师
在2018年5月23日 17:53，xtgjfge<notifications@github.com> 写道：

haha

**Comment by 18410717913** [comment]
Sorry, I have been too busy these days to see your mail in time. I can not give you any reply to the questions you mentioned.





At 2018-05-24 11:04:15, "weilian-peng" <notifications@github.com> wrote:
do you know how to solve that question??




发自网易邮箱大师
在2018年5月23日 17:53，xtgjfge<notifications@github.com> 写道：

haha

**Comment by gg22mm** [comment]
我想知道，用了这个，那object-c 与 安卓 他们开发的app 怎么用？

**Comment by Yietion** [comment]
请问单文件上传的话如何重新选择文件？

**Comment by Lc3586** [comment]
> 教程上有说得不明确的地方，请留言告诉我，谢谢！

老哥，文件大小限制设置了4G之后，选择3G的文件，会提示文件大小超过限制。是不是和其他什么设置冲突了啊。

**Comment by youll604852071** [comment]
楼主问下按钮没办法自定义吗？

**Comment by xiaoxb** [comment]
> 以下评论将自动发布在[Web Uploader 快速开始教程](http://fex.baidu.com/webuploader/getting-started.html)页面里面。

还是demo来的快

**Comment by AMengF** [comment]
您好，为什么我的会提示上传出错

**Comment by wzfxue** [comment]
请问 webuploader uploadProgress上传进度依赖服务端吗？为啥我上传本地有进度正常显示，如果经过服务端转发到七牛云的话进度就不对了。

**Comment by ofoo** [comment]
手机端无法选择多张图片

**Comment by ZeroGF** [comment]
> 以下评论将自动发布在[Web Uploader 快速开始教程](http://fex.baidu.com/webuploader/getting-started.html)页面里面。

这个插件能在ie上传文件夹吗

**Comment by ofoo** [comment]
这个插件支持苹果11吗

**Comment by gbl20** [comment]
上传出错报No input file specified.，是什么意思呢？？第一次用

**Comment by wooego** [comment]
> 教程上有说得不明确的地方，请留言告诉我
uploader的accept参数里，分别有title,extensions和mimeTypes。
请问mimeTypes是在显示文件时进行过滤，而extensions是扩展名不在其中的不处理么？
另外，title参数没看到效果，请问这个是在哪显示？

**Comment by Qizys** [comment]
auto设置为true,为什么文件传不到后台?

**Comment by wudinana** [comment]
我在ie9上点击按钮，选择文件弹窗没弹出，有没有完整的写这个项目的代码，我就是想要第一种demo的效果，不知道自己哪出问题了，对比一下

**Comment by rtcatc** [comment]
> 小白请教,代码中"$img"或者"$list";
> '$'后面直接跟字母,这种写法是来自哪里,不太明白

**Comment by rtcatc** [comment]
<script>

**Comment by zzq354943623** [comment]
请问为什么我写的demo不进监听事件呢？

**Comment by peng-ly** [comment]
请问怎么设置前置还是后置的图片上传呀，我没在demo上看到呢

**Comment by JessicaStart** [comment]
怎么在上传时候把文件名做限制呀
