### ISSUE TITLE
在分片上传成功后，如何接收服务器返的数据？

### ISSUE THREAD

**Issue by starboyss** [fex-team/webuploader#746]
在分片上传成功后，如何接收服务器返的数据？需要对服务器返回的数据来确定下一个分片上传必要参数？

**Comment by frozamilan1899** [comment]
每一片上传完成会调用uploadAccept事件，在回调中可以拿到服务器返回的数据：
uploader.on('uploadAccept', function(block, result) {
       // do something
});

**Comment by starboyss** [comment]
好，谢谢
