### ISSUE TITLE
为何上传按钮的点击事件会触发两次？

### ISSUE THREAD

**Issue by justin-zhengyi-wu** [fex-team/webuploader#776]
### 场景一：
- 打开[Getting Started](http://fex-team.github.io/webuploader/getting-started.html)，
- 打开开发者工具
- 运行下面的代码，给上传按钮加上一个点击事件处理器：

``` js
$('#picker').on('click', function() { console.log('Clicked.'); });
```
- 点击「选择文件」按钮，可以在控制台看到事件处理器两次被调用。
### 场景二：

步骤同上，用mouseenter事件。
结果是，事件处理器只会被调用一次。

**Comment by justin-zhengyi-wu** [comment]
扒了下源码，发现 label 的点击处理函数里会再次触发 input[type=file] 的 click 事件。而这两个事件都会冒泡至外面的 picker节点上。

尝试着 在 [这一行](https://github.com/fex-team/webuploader/blob/master/src/runtime/html5/filepicker.js#L25) 下加上：
```js
event.stopPropagation();
```
当然上面那行要加上对应的参数 event。

这样就没有问题了。
不过不知道这样改是否正确，或者有副作用。(没有查看源码其他部分)

有人能帮忙指点一下吗？ 多谢。

**Comment by yonglih** [comment]
选择文件按钮上的click事件是不被触发的，mouseenter事件会被触发两次。

**Comment by justin-zhengyi-wu** [comment]
@yonglih ，多谢您的回复。
您提到的`选择文件按钮`是指的[Getting Started](http://fex-team.github.io/webuploader/getting-started.html)页面上的`$('#picker')`吗？
我尝试给它加上click事件的句柄后，实现运行确实是触发了两次（步骤见我原问题）。
能否帮忙再看下，谢谢。

**Comment by justin-zhengyi-wu** [comment]
[测试视频](http://v.youku.com/v_show/id_XOTI1ODQ0MDEy.html)

**Comment by Xiaoqii** [comment]
你这个是跨域调用后台服务器嘛，如果是的话就看看https://my.oschina.net/freelili/blog/829658这个链接

**Comment by justin-zhengyi-wu** [comment]
> 你这个是跨域调用后台服务器嘛，如果是的话就看看https://my.oschina.net/freelili/blog/829658 这个链接

@Xiaoqii ，谢谢您的回复，这已经是3年前的问题了。刚查看了下，这个问题已经被修复，见： https://github.com/fex-team/webuploader/commit/bc5d0177095272ea9e082a7d04ad2454c6e7a464
（修复方案也是我上面给出的办法）。
不是跨域调用后台服务器，纯前端交互。

**Comment by justin-zhengyi-wu** [comment]
fixed at https://github.com/fex-team/webuploader/commit/bc5d0177095272ea9e082a7d04ad2454c6e7a464
