### ISSUE TITLE
发布 npm 模块, 方便 webpack 当中使用

### ISSUE THREAD

**Issue by jiyinyiyong** [fex-team/webuploader#780]
用 Webpack 安装的话, 放在 `node_modules/` 是比较好的选择,
我尝试了一下, 里边引用的 jQuery 大概要特殊处理, 绑定 `window.jQuery` 对象, 用插件即可,
https://github.com/webpack/expose-loader
另外有个问题是这个项目没有对应的 npm 包, 下载安装通过 `git+ssh` 协议非常慢的样子..
怀疑是 npm 通过 `git clone` 搞的, 因此建议发布一个 npm 包.

**Comment by CodingMonkeyzh** [comment]
:+1: 
这个项目的repo 好大（33.59 MiB），希望尽快发布官方 npm 包

**Comment by meakchen** [comment]
能不能出个具体点的文档啊

**Comment by jiyinyiyong** [comment]
Someone has done it https://www.npmjs.com/package/webuploader
Closing.
