### ISSUE TITLE
文件上传完成后等待响应时被掐断(在120s左右)

### ISSUE THREAD

**Issue by meilihao** [fex-team/webuploader#789]
从文件上传完成后开始计时,如果服务器响应需超过2分钟时,Post请求会在120s时被取消,导致Web Uploader 没有拿到响应结果.

ps:
1. 由于服务器处理流程复杂,有时服务器响应结果需超过2分钟.,视上传文件大小而定.
2. 试过ie11和chrome40,都是在120s左右被掐断
3. 服务器程序没有设置超时.

**Comment by meilihao** [comment]
uploadError事件的reason内容是"timeout"

**Comment by 2betop** [comment]
Webuploader 有超时中断，看下配置项！可以关

**Comment by meilihao** [comment]
Transport.options.timeout?可是修改后没有效果.而且在官网的文档中未找到超时设置项.

**Comment by 2betop** [comment]
直接就是 `timeout: 0`

**Comment by meilihao** [comment]
能不关掉timeout而是延长超时时间吗?比如延长到10m之类的.上次我改为10m,可是连接还是在2m后断开.

**Comment by 2betop** [comment]
这是默认值

```
timeout: 2 * 60 * 1000, 
```

你可以通过 WebUploader.create 的时候指定新值。试下 10 * 60 * 1000 看看

**Comment by meilihao** [comment]
我上次是直接修改了webuploader.min.js中timeout的值,可惜不起作用.

**Comment by meilihao** [comment]
WebUploader.create指定timeout有效.
