### ISSUE TITLE
如何用browserify或者webpack引入？

### ISSUE THREAD

**Issue by limichange** [fex-team/webuploader#797]
jquery不一定都是全局暴露的吧？

**Comment by suigezi** [comment]
同样碰到了这个问题，同问

**Comment by xiabin** [comment]
我也同样遇到这个问题

**Comment by xiabin** [comment]
webpack 中这样写
require('expose?$!expose?jQuery!jquery');
require('script!../lib/webuploader/webuploader.js')
就可以搞定

**Comment by Foreverofh** [comment]
@xiabin  不行啊

**Comment by TragueZw** [comment]
@Foreverofh 这样就可以了，我用的是webpack2
 {
      test: require.resolve('/jquery-3.0.0.min.js'),
      use: [{
        loader: 'expose-loader',
        options: 'jQuery'
      }, {
        loader: 'expose-loader',
        options: '$'
      }]
    },
