### ISSUE TITLE
如何修改默认的上传文件名

### ISSUE THREAD

**Issue by lichunqiang** [fex-team/webuploader#838]
现在默认的 file name 是 file， 怎么修改默认提交的file名？

**Comment by chaegumi** [comment]
{
 fileVal:'你要的名字'
}

http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_options

**Comment by lichunqiang** [comment]
我晕，昨晚没看到。。。

**Comment by sunny-xue** [comment]
确定这个鸟东西可以用？
