### ISSUE TITLE
做了简易版（不验证md5）的断点续传，但发现“超过每个分片大小的图片”上传时只会计算第一个分片

### ISSUE THREAD

**Issue by matrixkeygit** [fex-team/webuploader#861]
作者你好，看了你的关于断点续传的伪代码后，我稍微调整了一下逻辑，去掉了对文件or分片的md5验证，实现了不太精确的断点续传。
大致逻辑是：
before-send-file事件中，把file.id和next（默认为0，初始byte数）放入键值对数组中。这个数组叫nexts。
before-send事件中，判定block.file.id在nexts中的next值 和 block.start的大小，若next大于start则跳过该分片，反之则继续。
uploadBeforeSend事件中，给header对象增加Content-Range属性，这个属性的值格式为“bytes 0-5000/239877”。
后台上传方法中，获取请求表头中的range属性，解析“接收到的分片的起始位置和结束位置”，并与“服务器中的这个文件的大小比较”。
若服务器中不存在这个文件，则创建它，以流的方式添加文件数据。
若服务器中这个文件存在，则读取它的大小，与传过来的结束位置比较。若文件大小超过结束位置，则返回文件大小位置，啥也不干。若文件大小小于结束位置，则把这块分片添加到文件中，并返回结束位置。（简单来说，后台方法保存后，返回已接收的文件大小值。）
后台方法执行后，前台触发uploadAccept事件，这里可以根据参数获取file.id和最新的已接收文件大小，然后就去更新nexts中该file.id的next值。
就这样，下一个分片继续重复以上过程。

我设置了分片大小是5×1000×1000，大约5M不到，测试了上百M的各种文件，秒传和断点续传都OK。
但是当测试“大于5M”的图片（图片是高像素中国地图，大小约20M）的时候，发现只会切第一个分片，而这个分片的执行过程，也是按照上面的逻辑的，完全无误。执行完“第一个分片的uploadAccept事件“后，紧接着执行的事件是uploadSuccess，再然后是uploadComplete和uploadFinished。

也就是说，直接跳过”剩余的分片“了。。我还特地找了另外一张15M的图片进行测试，结果一样。

最后补上console.log信息。

高达一亿像素的中国地图.jpg文件执行before-send-file事件，文件总大小：22020000 
执行uploadStart事件：某个文件开始上传前触发，一个文件只会触发一次。 
第0个分片开始执行的before-send事件
第0个分片执行uploadBeforeSend事件：当某个文件的分块在发送前触发，主要用来询问是否要添加附带参数，大文件在开起分片上传的前提下此事件可能会触发多次。
执行uploadProgress事件：上传过程中触发，携带上传进度。当前进度：1
执行uploadProgress事件：上传过程中触发，携带上传进度。当前进度：1
第0个分片执行uploadAccept事件，返回的next是：34075（题主写，34075表示第0个分片的大小）
执行uploadSuccess事件：当文件上传成功时触发
执行uploadComplete事件：不管成功或者失败，文件上传完成时触发 

请作者抽空看看，实在感谢。

等测试完这些，我也将扩展成用md5验证的断点续传。

**Comment by matrixkeygit** [comment]
新的测试发现这样一个问题，文件总大小，在被分出第一个片之后，总大小改变了！
高达一亿像素的中国地图.jpg文件执行before-send-file事件，文件总大小：22020000 
执行uploadStart事件：某个文件开始上传前触发，一个文件只会触发一次。
第0个分片开始执行的before-send事件 
这个分片的属性：
分片号：0 
分片总数：1 
分片起始点：0 
分片结尾点：34075 
分片所属文件总长度：34075

**Comment by 2betop** [comment]
是这样的，图片默认是会压缩的。压完后就只有那么大了。

**Comment by matrixkeygit** [comment]
@2betop
所噶！明白了，是我看API不仔细。谢谢回复啊～

**Comment by xiaoji201509** [comment]
关于断点续传的伪代码，在哪里可否发一个连接，谢谢了
