### ISSUE TITLE
怎么才能实现上传一个文件夹呢？

### ISSUE THREAD

**Issue by glgydxc** [fex-team/webuploader#892]
怎么支持上传一个文件夹下的所有文件？包括子目录

**Comment by glgydxc** [comment]
多途径添加文件

支持文件多选，类型过滤，拖拽(文件&文件夹)，图片粘贴功能。

**Comment by coolboybobo** [comment]
我也想知道怎样，麻烦谁知道说下？

**Comment by glgydxc** [comment]
上传文件夹功能在谷歌浏览器下是可用的，其他浏览器支持的不好。

**Comment by coolboybobo** [comment]
那目前多浏览器支持好的的方式一般采用什么呢？
