### ISSUE TITLE
dnd 的解绑接口

### ISSUE THREAD

**Issue by suyu34** [fex-team/webuploader#895]
在某些情况下需要后台上传，所以uploader对象暂时不能destroy掉，但是这时新的页面需要禁止拖拽行为，需要把 dnd 的拖拽行为解绑掉，有这样的解绑接口吗？
我看了下代码，dnd对象自己是有 destory 函数进行事件解绑的。不知道这个对象能访问到么？

**Comment by kevin123de** [comment]
同问

**Comment by kevin123de** [comment]
请问有解决吗？

**Comment by suyu34** [comment]
```
dnd = _.find(webuploader._widgets, (obj) -> return obj.name is 'dnd')
dnd?.destroy?()
```

@kevin123de 我用了一个黑科技的方法来做这件事情，目前我这边是有效的，你可以尝试一下。
