### ISSUE TITLE
accept如何设置，才能仅接受后缀名为dcm和后缀名为空的的文件

### ISSUE THREAD

**Issue by yanchengv** [fex-team/webuploader#898]
accept:{
                title : 'dcm后缀的文件', 
                extensions : ''
            }
要上传的文件为demo.dcm或者demo（无后缀名），请问怎么设置才能仅仅接收这两个文件

**Comment by zqalyc** [comment]
accept:{
title : 'dcm后缀的文件', 
extensions : 'dcm'
}
上面写法是正确的！
我理解错了。。。，原来设置extensions ：‘dcm’后弹出框是可以看到其他文件的，但是添加不到序列中。要是在弹出的对话框中直接把要过滤的文件变成不可选，这就用户提交就更好了
