### ISSUE TITLE
多文件上传

### ISSUE THREAD

**Issue by imgaohao** [fex-team/webuploader#913]
webuploader多文件上传是一个个文件单独提交的。
怎么让多个文件一起提交啊（数组式提交）？

**Comment by LSL1618** [comment]
没用的，webuploader只能一次请求上传单个文件，有几个文件就发送几次请求。而我们想要的是不管是单个文件还是多个文件，只发送一次请求就行了。webuploader官方宣传的多文件上传误导我们了。

**Comment by wujianyi** [comment]
有没有多个文件，只发送一次请求的好点的jquery推荐

**Comment by LSL1618** [comment]
换一个上传组件不就得了，不一定非得用webuploader。至于哪个符合你的需求，那我就不知道了。自己去网上搜索吧。

**Comment by WenTao-Love** [comment]
楼主 请现在问题解决了吗？他可以支持一次性选择1000个以上的文件上传吗？
