### ISSUE TITLE
上传按钮点击区域大小

### ISSUE THREAD

**Issue by imgaohao** [fex-team/webuploader#914]
上传按钮点击区域大小在哪里设置，好像没有，自动适配的吗？

**Comment by gaohaoqq** [comment]
![Uploading 20140910061531_26693.png . . .]()

**Comment by gaohaoqq** [comment]
![Uploading 20140910061531_26693.png . . .]()

**Comment by lrzw32** [comment]
请问这个是怎么解决的，我这边的点击区域只有1px

**Comment by flyfreely2014** [comment]
同问

**Comment by lixiaoyu** [comment]
同问  点击区域有点小啊

**Comment by LSL1618** [comment]
自己修改样式，这个没有配置项。
