### ISSUE TITLE
问下上传完毕，下次编辑的时候如何能显示上传成功的图片。

### ISSUE THREAD

**Issue by vicente007** [fex-team/webuploader#947]
研究了一天没找到方案，求官方帮忙~

**Comment by ANGULAR-X** [comment]
我做的一个项目是，使用webuploader文件上传到文件服务器，下次修改时，做一次动态下载操作，将图片以流的方式返回，即可查看

**Comment by vicente007** [comment]
@ANGULAR-X 谢谢回答，这方面接触不多，有没有demo参考一下，或者相关文档~感激不尽~

**Comment by vicente007** [comment]
@ANGULAR-X  另外在第二次查看的时候，是否要重新初始化uploader？如果要初始化的话要改动什么地方吗

**Comment by vicente007** [comment]
问题搞定了~

**Comment by CuriousZhang** [comment]
朋友能告知下是怎么搞定的么

**Comment by niejiaqin** [comment]
求解决办法

**Comment by zhujinhu21** [comment]
@vicente007  你是怎么解决的
