### ISSUE TITLE
上传单文件的时候，选择上传第二个文件怎么把第一个替换掉

### ISSUE THREAD

**Issue by XZAKE** [fex-team/webuploader#982]
上传单文件的时候，选择上传第二个文件怎么把第一个替换掉

**Comment by lizhouyang** [comment]
在加入队列的时候，或者之前，将第一个file从队列中删除。file从队列中删除之后，貌似只是标识他删除，但是还是在那个getfiles里面。个人意见

**Comment by ANGULAR-X** [comment]
单文件添加时，添加前可以试试API 里面reset()这个方法。

**Comment by XZAKE** [comment]
参照官方例子，已经解决

**Comment by lizhouyang** [comment]
官方例子是怎么样子的，我怎么没有找到？请给出答案！

**Comment by XZAKE** [comment]
![Uploading image.png…]()

**Comment by XZAKE** [comment]
@lizhouyang 
![e8640daa-c171-4940-b845-17ebac322375](https://cloud.githubusercontent.com/assets/2064795/7950443/49bedda2-09cd-11e5-81e5-77f592be29fd.png)

**Comment by lizhouyang** [comment]
恩，学习了~多谢~

**Comment by yinxiangbo** [comment]
这样会有一个bug，选择文件1，然后在选择文件2，弹出对话框点击取消或者关闭对话框后，会导致文件1被remove，无法上传

**Comment by XZAKE** [comment]
@yinxiangbo 需求就是把第一个移除，不需要移除就不用这样考虑了。。。

**Comment by ixiaoq** [comment]
在fileQueued事件里处理

 // 限制上传数量
// 如果超过限制数量，重置uploader，并添加当前文件
setTimeout(function () {
    var fileArr = uploader.getFiles();
    if (fileArr.length > 1) {
        uploader.reset();   // 重置
        uploader.addFiles(file);
        console.log(uploader.getFiles());
    }
}, 500);

**Comment by ixiaoq** [comment]
在fileQueued事件里处理

// 限制上传数量
// 如果超过限制数量，重置uploader，并添加当前文件
setTimeout(function () {
    var fileArr = uploader.getFiles();
    if (fileArr.length > 1) {
        uploader.reset();   // 重置
        uploader.addFiles(file);
        console.log(uploader.getFiles());
    }
}, 500);

**Comment by ixiaoq** [comment]
在fileQueued事件里处理
    
    // 限制上传数量
    // 如果超过限制数量，重置uploader，并添加当前文件

     setTimeout(function () {
        var fileArr = uploader.getFiles();

        if (fileArr.length > 1) {
             uploader.reset(); // 重置
             uploader.addFiles(file);
        }
     }, 500);
