### ISSUE TITLE
后台代码能接收到参数，但是接收不到文件

### ISSUE THREAD

**Issue by ztmsimon** [fex-team/webuploader#988]
我使用的是.NET MVC4 ，现在出现了个问题，后台代码中的public ActionResult UpLoadProcess(string id, string name, string type, string lastModifiedDate, int size, HttpPostedFileBase file)
这些参数中前面的所有参数都有值，并且也都是对的，但最后file那个参数传递进来的时候就是null，知道是怎么回事吗？

**Comment by xakoy** [comment]
我也是用mvc4 都没问题的，你拿Fiddle看一下上传的数据，有可能是file这个参数名不对，所以是null，你看一下请求的正文的里面名字叫什么。
